### ISSUE TITLE
Drag placeholder Highlighter Postion

### ISSUE THREAD

**Issue by YashPrince** [GrapesJS/grapesjs#1410]
@artf When we set some margin from top to the container and want to drag some element inside it then 
Drag placeholder Highlighter position is not seems right as it included margin also and it's showing top of 
the element from where margin given. How can I show Drag placeholder Highlighter inside the container only not outside it so that it will less confusing to users. Any Help would be appreciated. 
![placeholdererror](https://user-images.githubusercontent.com/40828744/45250836-76b78500-b359-11e8-8074-3369b4463fda.png)

**Comment by artf** [comment]
Create a live demo, please

**Comment by alextychan** [comment]
Hi, I am new and would like to help contribute. May I know where can I start or what files I should be looking at in general? Any help/suggestion is much appreciated. @artf

**Comment by artf** [comment]
Closing the issue as it seems already to be solved.
