### ISSUE TITLE
Inline CSS Comments break Code Manager

### ISSUE THREAD

**Issue by emilsedgh** [GrapesJS/grapesjs#1577]
Apparently this is valid piece of html and css:

`<div style="color: red; /* height 200px; */; font-weight: bold;">`

(Hence the commented out _height_ property)

Grapesjs has trouble dealing with such attribute as the style attribute on the model is stored as this:

![screenshot_20181113_165603](https://user-images.githubusercontent.com/120439/48452681-0405c400-e765-11e8-83a6-0d4c46a2cd09.png)

The big problem is that CssGenerator's `buildFromObject` considers `/*` as part of the rule name for `/* height`, and concatenates it the whole css string. So the css code is basically _commented out_ when it reaches this model and is rendered unusable blob of commented out css.

Obviously the real fix is not on CodeManager. Whoever parses `/* height` to be a rule name is making a mistake.

**Comment by artf** [comment]
Hi Emil, I tried this https://jsfiddle.net/37n5691f/ but can't see the issue

**Comment by emilsedgh** [comment]
Alright I finally managed to reproduce this again. Reopening with [better fiddle](https://jsfiddle.net/nshc9wak/).

The code inside gjs is

```html
  <p style="/* color: #ffffff; */"></p>
  <span style="color: red;">Bar</span>
```
The CSS retrieved by `editor.getCss()` is:

```css
* { box-sizing: border-box; } body {margin: 0;}.c620{/* color:#ffffff;}.c629{color:red;}
```

The bug is that the `/* color:#ffffff;` doesn't have the closing comment tag. Therefore, it'd render any css that comes after it.

My apologies for the late response.

**Comment by artf** [comment]
Thanks @emilsedgh  Ok, I think we have to improve the [style attribute parser here](https://github.com/artf/grapesjs/blob/c1fb490a73adefb0fa073f37bef4e6178d9321a8/src/parser/model/ParserHtml.js#L64)

Suggestions are welcome

**Comment by artf** [comment]
> I would be a bit worried of corner cases the regexp might fail and also the performance impact, but that'd be the easiest way to solve it.


Yeah, regexp might be the "easiest", but is also my concern the performance impact. I was thinking about something, IMHO, simpler.

```js
while (str.indexOf('/*') >= 0) {
    const start = str.indexOf('/*');
    const end = str.indexOf('*/') + 2;
    str = str.replace(str.slice(start, end), '');
 }
```

It might be a case to setup a test case with https://jsperf.com
