### ISSUE TITLE
Customize the navigator

### ISSUE THREAD

**Issue by minuwan** [GrapesJS/grapesjs#1847]
Is there any way to customize the view of the navigator/layers panel? I need to display an icon in front of each item in the navigator.

**Comment by NicoEngler** [comment]
I am not sure what "the navigator" is but since you can create your own panels and whatever, you can customize every bit of the visuals.

Can you be more precise on where you try to add your icons?

**Comment by minuwan** [comment]
@NicoEngler Navigator is the [layers panel](https://github.com/artf/grapesjs/tree/dev/src/navigator), GrapesJS called it "The Navigator". Currently, it only [contains few configs](https://github.com/artf/grapesjs/blob/dev/src/navigator/config/config.js), but the render it in a different layout or add an icon to a layer item is not possible it seems.

**Comment by artf** [comment]
@minuwan well actually the view already renders the icon https://github.com/artf/grapesjs/blob/94e295ef919dceaade90a3aa36355f2e23935657/src/navigator/view/ItemView.js#L47 but the idea of customizing the render of layers it's not bad.

**Comment by artf** [comment]
https://grapesjs.com/docs/modules/Layers.html#customization
