### ISSUE TITLE
[BUG] Link isn't editable on EDGE

### ISSUE THREAD

**Issue by MisterFK** [GrapesJS/grapesjs#2025]
Hi,

The link component isn't editable on EDGE.
I try on the grapesjs demo and there is the same issue.
Do you know how to resolve this problem please?

Thanks!

**Comment by kkifa** [comment]
I'm seeing the same behavior in latest version of Edge. 
After dragging the 'Link' or 'Button' block onto canvas I can select the label text by double-clicking, and I can insert an 'I' beam by single-clicking inside the selection, but inserting text does not work.

**Comment by Zachary1748** [comment]
You still use/support IE? 🤔 Let it DIE ALREADY...

**Comment by artf** [comment]
Closing this as doesn't seem to be an issue anymore
