### ISSUE TITLE
[BUG] Gradient plugin is interfering with background-image

### ISSUE THREAD

**Issue by alikabeer32** [GrapesJS/grapesjs#2138]
The background-image url is getting wrapper around by linear-gradient() function like so
```css
background-image: -webkit-linear-gradient(path/to/image.jpg);
```
Even though I assigned gradient to 'background' property instead of 'background-image'
```js
          editor.StyleManager.addProperty('decorations', {
          name: 'Gradient',
          property: 'background',
          type: 'gradient',
          defaults: 'none'
        });
```

I can't reproduce the bug in the demo of either grapesjs or the plugin because in neither of them have the two features (background image and gradient ) been used together.

**Comment by alikabeer32** [comment]
UPDATE: I know it's a very hacky fix but what I did is replace every 'backgroundImage' with just 'background' in the grapesjs-style-gradient.min.js file of the plugin. And now it works like I need it to.

**Comment by artf** [comment]
Does anyone is able to create a reproducible demo, please?

**Comment by robsonsobral** [comment]
I'm sorry, guys. I can't find time to work on this project again until next week, I guess.

**Comment by artf** [comment]
Can someone check if the latest release fixes the issue, please?

**Comment by alikabeer32** [comment]
God damn I'm back here lol. Still not fixed I guess. Somebody helpp!!

**Comment by alikabeer32** [comment]
@artf latest release doesn't fix the issue I think

**Comment by artf** [comment]
Closing this one as it's quite old and no reproducible demo was provide so far
