### ISSUE TITLE
[Bug] Video boolean attributes breaks on import

### ISSUE THREAD

**Issue by giorgiosjames** [GrapesJS/grapesjs#2357]
**Explanation**
_Using https://grapesjs.com/demo.html v0.15.8 on Chrome 77.0.3~ Windows 10 Pro Build 18362_
Importing a Video component with any Boolean attribute (controls, loop, autoplay) using the import modal will break all boolean attributes on the component until the component is deleted.

**Reproduction Steps**
- Navigate to https://grapesjs.com/demo.html
- Clear the canvas
- Drag in a 'Video' Block
- Ensure the 'Controls' boolean attribute is checked (should be by default)
- Open the import code modal
- Click import
- Boolean attribute traits no longer work on the component
- Also can't re-import the video with the boolean attribute removed

**Screencast**
Screencast showing video working as expected, and then the bug.
![grapesVideoBug](https://user-images.githubusercontent.com/33015856/67815378-e60eac00-fafa-11e9-864b-6a66a5d8df65.gif)

**Comment by artf** [comment]
At first look the issue might be here:
https://github.com/artf/grapesjs/blob/a850a305b80b8f86c0e7e4fb92b6492c2e5a1957/src/dom_components/model/ComponentVideo.js#L115-L117

indeed in the export/import I'd expect just `... controls>` and not `... controls="controls">`. The HTML code generator should use single attributes when encounters Boolean `true` values, so the first try might be
```js
if (this.get('loop')) attr.loop = true;
...
```
