### ISSUE TITLE
BUG: update listener triggered on initial load

### ISSUE THREAD

**Issue by kuhelbeher** [GrapesJS/grapesjs#3071]
Hello! I found weird bug with update listener. It's triggered on initial load if html code has <img> tag with class attribute:
```javascript
const editor = grapesjs.init({
  container: "#gjs",
  storageManager: { type: 0 },
  plugins: [],
  components: `
    <img src="https://images.unsplash.com/photo-1602536062611-8996fd6f8149?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1998&q=80" alt="Some alt text" class="centered"/>
  `
});

editor.on("update", () => {
  console.log("udpdated");
});
```

You can check live demo in this [sandbox](https://codesandbox.io/s/grapes-update-listener-bug-9oizp?file=/src/index.js)

**Comment by artf** [comment]
I'm not sure why it's happening but I'd not assign a high priority to the issue for 1 false-positive update. So, if anyone would like to help in debugging this I'd appreciate

**Comment by artf** [comment]
Shouldn't be an issue anymore
