### ISSUE TITLE
BUG: block.get('category') returns different results in Chrome and Firefox

### ISSUE THREAD

**Issue by kuhelbeher** [GrapesJS/grapesjs#3257]
Hello, I've hit weird bug when I tried to get block category. `block.get('category')` returns object in Chrome, but in Firefox the same code returns string:

![image](https://user-images.githubusercontent.com/37115006/106619453-4780be80-6579-11eb-90c6-8b33f197891c.png)
Left - Chrome, rIght - Firefox

Also with enabled [adblock](https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom/related?hl=ru) or [selenium](https://chrome.google.com/webstore/detail/selenium-ide/mooikfkahbdckldjjndioackbalphokd) extensions this code also returns string. Some other extensions might cause this problem too, so try it in incognito mode.

You can check the issue [here](https://codesandbox.io/s/grapes-category-issue-xfbll?file=/src/index.js)

**Comment by xinnai** [comment]
@kuhelbeher I got same issue, did you resolve your problem?

**Comment by artf** [comment]
This seems to be solved with the latest version of GrapesJS
