### ISSUE TITLE
BUG: Color Picker Transparency slider is at 0 in firefox.

### ISSUE THREAD

**Issue by mhowey** [GrapesJS/grapesjs#3260]
The color picker in grapesjs does not work the same between Chrome and Firefox. When you open the picker on a selected component that has never had it's background color set before (for instance...) the color picker opens with opacity set to 100% in Chrome and 0% in Firefox.

The issue is that the user may hot even look at this transparency slider when using Firefox and will try to change colors unsuccessfully, not realizing that the opacity is at 0%.

**Expected Behavior:** In all browsers the color picker will open with the transparency set to 100% by default when the component that is being styled has never had its background color specified.

**Actual Behavior:** In Chrome, the color picker works as expected. In Firefox the color picker always initially opens with the opacity slider at 0%.

Thanks in advance for your great project!!

**Version:**
Latest 

*You can get the version by typing `grapesjs.version` into the console*

**Are you able to reproduce the bug from the demo?**

[X] Yes

**Comment by mhowey** [comment]
@artf Another difference to note between Firefox and Chrome is what is displayed in the palette. Firefox shows a transparent box while Chrome shows a gray one.

**Comment by artf** [comment]
Seems to be solved on the latest Firefox version
