### ISSUE TITLE
BUG: CleanId function not working with MJML code

### ISSUE THREAD

**Issue by ThomasPof** [GrapesJS/grapesjs#3282]
CleanID is still not working for MJML code, even on latest version of grapesJS (0.16.41)

It's related to this closed issue : https://github.com/artf/grapesjs/issues/3276

```
      htmlOpts.attributes = (mod, attrs) => {
        const { id } = attrs;
        console.log(attrs) // this log works well with HTML dom, but not in MJML and I don't know why
        if (
          id &&
          id[0] === 'i' &&
          !mod.get('script') &&
          !mod.get('attributes').id &&
          idRules.indexOf(id) < 0
        ) {
          delete attrs.id;
        }
        return attrs;
      };
```

This function is not reading MJML tags : `attrs` are empty, and I cannot find why...

**Comment by artf** [comment]
The id issue should be solved already on the latest mjml plugin release
