### ISSUE TITLE
BUG: The changesCount parameter should be reset to zero when we undo the images

### ISSUE THREAD

**Issue by marcepoblet** [GrapesJS/grapesjs#3290]
**Version:**
v0.16.41

**Are you able to reproduce the bug from the demo?**

[ ] No

**What is the expected behavior?**
The changesCount parameter should be reset to zero when we undo the images

*Describe the bug **detailed***
Steps:
- add an image
- delete the image
- undo the changes

We should see the changesCount parameter should be reset to zero.

**What is the current behavior?**

The changesCount parameter  is incremented and not is zero.

**Are you able to attach screenshots, screencasts or a live demo?**

[ ] Yes (attached a video)

https://user-images.githubusercontent.com/64096863/109162404-ee124680-7756-11eb-9668-b1909b913831.mp4

**Comment by GayathriGuru** [comment]
Hi! @marcepoblet can you please share the part of your code which you used to define the changesCount variable?

**Comment by GayathriGuru** [comment]
Hi! @marcepoblet can you please share the part of the code which you used to define the changesCount variable to get it incremented?

**Comment by artf** [comment]
Closing this as I don't see any substantial benefit for this functionality
