### ISSUE TITLE
BUG: inspector overflow broken

### ISSUE THREAD

**Issue by anatoli-dp** [GrapesJS/grapesjs#3463]
## WARNING
READ and FOLLOW next 3 steps, then REMOVE them before posting the issue

1. Follow CONTRIBUTING Guidelines https://github.com/artf/grapesjs/blob/master/CONTRIBUTING.md
2. Do a quick SEARCH first, to see if someone else didn't open the same issue
3. All relative statements/questions have to be filled/answered, otherwise, the issue might be CLOSED
4. JSFiddle Starter template https://jsfiddle.net/szLp8h4n
5. CodeSandbox Starter template https://codesandbox.io/s/1r0w2pk1vl

**Version:**

*You can get the version by typing `grapesjs.version` into the console*

**Are you able to reproduce the bug from the demo?**

 - [ x] Yes
 - [ ] No

**What is the expected behavior?**
when stacking anything within each other the inspector should make appropriate room for the text of the component and its controls properly positioned

*Describe the bug **detailed***
when stacking items past the inspectors width the rows expand but no text is seen and controls are not properly positioned

**What is the current behavior?**
as stated above (idk if i even explain it well but screenshots are provided)

*Describe the bug **detailed***

**Are you able to attach screenshots, screencasts or a live demo?**

 - [ x] Yes (attach)
 - [ ] No
![Screenshot from 2021-05-18 09-50-01](https://user-images.githubusercontent.com/75029364/118674474-6bca7900-b7bf-11eb-97d1-d9eb15a92353.png)
![Screenshot from 2021-05-18 09-50-07](https://user-images.githubusercontent.com/75029364/118674495-6f5e0000-b7bf-11eb-8c72-84fb38d8d9cf.png)
![Screenshot from 2021-05-18 09-50-15](https://user-images.githubusercontent.com/75029364/118674512-7258f080-b7bf-11eb-93e1-bd0aec929587.png)

**Comment by artf** [comment]
Yeah, unfortunately, the default layer panel is not that scalable, we need to rethink how is rendered

**Comment by anatoli-dp** [comment]
Maybe put the controls in the front of the text and then offset the entire box slightly for each indent or stacked item. That way u can stack them as far as you want without issue 🤷

**Comment by artf** [comment]
Yeah moving controls in font of the text sound reasonable (eg. and make them visible only when I hover the component).
Anyway, being not such a common case having so much messy structure I wouldn't put a lot of priority on this problem, but for sure it would cool to fix such a limitation.
If anyone is available for help, here you can find views of the Layer Manager: https://github.com/artf/grapesjs/blob/dev/src/navigator/view/ItemView.js

**Comment by artf** [comment]
Closing this one as seems already to be fixed
