### ISSUE TITLE
BUG: gjs-selected Style is Hardcoded

### ISSUE THREAD

**Issue by anlumo** [GrapesJS/grapesjs#3515]
This definition:

https://github.com/artf/grapesjs/blob/88249c38577852dc3c42047356a70a12066ee6ca/src/canvas/view/FrameView.js#L303-L306

is always appended to the frame. It contains the color definition for selected elements (that blue outline). This color cannot be changed, because there's an `!important` here. Since this is appended to the body, adding a stylesheet in the header does not override it, even when I use `!important` there as well.

For my use case, the critical issue is that I want to be able to print the document created in grapesjs, but printouts should not contain the selection outline. I can write `@media print { .gjs-selected { outline: none !important; } }`, but that won't do anything since it's overridden by this hardcoded css definition.

Also, being able to change the color to fit the page's corporate identity would be good.

**Comment by artf** [comment]
Hi @anlumo you're right, unfortunately, component status styles are rendered inside iframes. I've tried to put them outside by introducing [this option](https://github.com/artf/grapesjs/blob/614fad12b729c382b2444ca8b5e584f1dafc063a/src/canvas/config/config.js#L38-L39) but that doesn't handle multiple selections yet. So, at the moment, the only way to handle them properly is to use this option:
```js
grapesjs.init({
  // ...
  canvasCss: `
        .gjs-selected {
          outline: 3px solid red !important;
        }
   `,
})
```

**Comment by Ravi910680** [comment]
but in output shows  with blue outlined

**Comment by mingxin-yang** [comment]
![Snipaste_2021-09-10_12-04-41](https://user-images.githubusercontent.com/23076937/132798109-7672833e-ed9f-4323-82a3-0a44b650c0db.png)
![Snipaste_2021-09-10_12-05-27](https://user-images.githubusercontent.com/23076937/132798111-2284c4da-32e0-4717-9fa1-7cd080ada724.png)
how to set all the blue to red? @artf

**Comment by filipecheverrya** [comment]
Hi @mingxin-yang i belive that you have to follow the same rule that @artf said. But using the corresponding classes

```js
grapesjs.init({
  // ...
  canvasCss: `
    .gjs-tools .gjs-badge { /* for the label */
      background-color: red;
    }
    .gjs-toolbar { /* for the toolbar */
      background-color: red;
    }
  `,
})
```
