### ISSUE TITLE
Customize Blocks Styles - grapesjs Angular

### ISSUE THREAD

**Issue by hadeel94** [GrapesJS/grapesjs#3560]
I am new to grapes js , I am trying to make the blocks in a different style when dragging 
for example the image blocks 
1 -  when not dragged or hover takes style A .
2-  when hover takes style B .
3-  When dragged takes style C (when it is over the canvas).

can any one help me with this issue .

Thanks
![DASHBORAD – 12](https://user-images.githubusercontent.com/86350308/123074122-b45cfe00-d41f-11eb-9738-a7f53401c58e.png)
![DASHBORAD – 11](https://user-images.githubusercontent.com/86350308/123074131-b626c180-d41f-11eb-82b4-9f391fdbc7ff.png)
![DASHBORAD – 9](https://user-images.githubusercontent.com/86350308/123074144-b7f08500-d41f-11eb-9260-deb11828b31b.png)

**Comment by ronaldohoch** [comment]
Maybe with this events you can do it: https://grapesjs.com/docs/api/editor.html#available-events

**Comment by artf** [comment]
In such a case, probably a completely custom block manager UI is the only way (eg. rendered by your own BlockManager component in Angular). It should be possible already, but I'd prefer to take my time and update the [Blocks](https://grapesjs.com/docs/modules/Blocks.html) documentation with all the steps and examples necessary to build the BlockManager UI from scratch.

**Comment by hadeel94** [comment]
> In such a case, probably a completely custom block manager UI is the only way (eg. rendered by your own BlockManager component in Angular). It should be possible already, but I'd prefer to take my time and update the [Blocks](https://grapesjs.com/docs/modules/Blocks.html) documentation with all the steps and examples necessary to build the BlockManager UI from scratch.

Thanks for your response, I have other questions:
1- Can I change the color of the green indicator that appears when dragging any block? I am trying to change $color Green variable but doesn't work.
2- I am trying to custom assets manager like this image, is it possible ? or replacing the model is better? and once the image is uploaded the model must be closed 
![Untitled](https://user-images.githubusercontent.com/86350308/127760299-4590a336-589d-47f9-aead-81aada0da7b6.png)

3- can I change the position of RTE  as panel action on a fixed position .

Thank you very much, I would be glad if you answered my questions

**Comment by artf** [comment]
Closing this one as Blocks documentation was updated with a proper example for a [custom Block Manager UI](https://grapesjs.com/docs/modules/Blocks.html#customization)
