### ISSUE TITLE
BUG: Firefox issue when the user clicks on different component very fast

### ISSUE THREAD

**Issue by flowize-project** [GrapesJS/grapesjs#3857]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
You need to click very fast from one component to another component on the canvas and you will receive a js error "too much recursion" and the html content is gone.

The error is shown in line 1627 model/component.js with method "ensureinlist". We have several customer reporting this issue.

You can check the issue on this video: https://recordit.co/j9e1S6guW5

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arthuralmeidap** [comment]
hello @flowize-project ! hope you are good! In your issue you have posted GrapesJS demo link as reproducible link but the video was recorded with a custom grapesjs installation.
Could you try to record a video and reproduce the issue with the GrapesJS demo link??
