### ISSUE TITLE
BUG: Disabled drag and drop in preview

### ISSUE THREAD

**Issue by xQwexx** [GrapesJS/grapesjs#3939]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

v95

### Reproducible demo link

https://codesandbox.io/s/grapes-border-issue-forked-2c0ib?file=/src/index.js:10258-10261
### Describe the bug

**How to reproduce the bug?**
I am trying to create a custom component, which contains drag end drop feature,
and due to the fix of #2904 the draggable attribute is turned off altogether. 

**What is the expected behavior?**
The custom component that made intentionally  draggable could be previewed as such

**What is the current behavior?**
Currently all of the draggable events are disabled in preview

I am also open to make a pr just first I wanted to discuss which is the best way solve this issue,
or maybe this is a design decision of the project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Hi @xQwexx what would be your solution in such a case? We still need to keep the D&D disabled in the preview.
Can you also post your component code in order to understand better the use case?

**Comment by xQwexx** [comment]
Hi @artf I updated with a demo, also my suggestion would be that use the  `attributes: { draggable: 'true'}`, indicator if the component is draggable in preview and leave the drag handling for the component template like ` attributes: { draggable: 'true', ondrop: 'drop(event)' , ondragover: 'allowDrop(event)'}` I am not 100% percent sure how it is handled now, but I would change this draggable html tags for false if this attribute is not present, when we change to preview.

**Comment by vince83110** [comment]
I don't think a page builder should be used for such cases.
For example, if your drag & drop generates some actions (like ajax post to server to save new positions or w/e), what would you do ? allow ajax actions in preview mode ? do not save positions ? Seems overkilled. This is not a bug, it's a weird feature you are asking for.

**Comment by xQwexx** [comment]
>For example, if your drag & drop generates some actions (like ajax post to server to save new positions or w/e), what would you do ?
I would say yes because the preview view purpose is to test the code, so you can be sure that it works correctly after deployment. In this cases I would say it is the developer job to set up a development server so you not updating the prod server data. But I think that part optional because not every use case needs it.
