### ISSUE TITLE
Background color automatically changes to black

### ISSUE THREAD

**Issue by dev4322** [GrapesJS/grapesjs#4006]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://grapesjs.com/demo.html.

### Describe the bug

By default background color is none. 
When i click on color picker to change the background color and doesn't select any color from color picker. (closes color picker modal on clicking screen not on modal ). it automatically changes color to black.

you can reproduce this issue on official demo https://grapesjs.com/demo.html.

is there any way t fix this??

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
I'm not able to reproduce it, are you able to provide a screen recording of the issue?

**Comment by Kamran544** [comment]
@artf any solution for this issue?

**Comment by jloguercio** [comment]
I have the same issue, if you click outside the colorpicker it turn in black

**Comment by Vac1911** [comment]
Can confirm issue is still happening in version 0.19.4

**Comment by msyyn** [comment]
Hey, the issue could be that color picker is reset to "transparent" which some browsers handle as black in certain situations - maybe trying to reset color to rgba(0,0,0,0) or rgba(255,255,255,0) instead could help. Just a thought - not sure if this is the case. Could not replicate the issue myself.
