### ISSUE TITLE
BUG: Drag and drop not working well in case of RTL

### ISSUE THREAD

**Issue by YairNa** [GrapesJS/grapesjs#4015]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v96

### Reproducible demo link

https://jsfiddle.net/emgbo8k1/3/

### Describe the bug

**How to reproduce the bug?**
1. add the 3 columns block to the canvas
2. drag and drop in order to change the columns order

**What is the expected behavior?**
The drag and drop should set the position correctly

**What is the current behavior?**
The position of the columns after the drag and drop is not correct.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
editor.getWrapper().addClass("gjs-wrapper");

editor.Css.setRule('.gjs-wrapper', {
  direction: "rtl"
});
```
I added the code in the JSFiddle too

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sridhar391** [comment]
@YairNa We have also faced the same issue, please refer to the link https://github.com/artf/grapesjs/issues/4094

**Comment by JSSaint** [comment]
@YairNa  @sridhar391   it's not a RTL issue. chrome browser only we have face this issue. Firefox is working properly.
