### ISSUE TITLE
BUG: Unable to drop textable components into small text areas

### ISSUE THREAD

**Issue by DavidHarvey** [GrapesJS/grapesjs#4294]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v100

### Reproducible demo link

https://jsfiddle.net/ob0ajh67/

### Describe the bug

**How to reproduce the bug?**
1. Have a single line of text that has no additional sizing styles (such as padding or explicit height).
2. Attempt to drag and drop a textable block into that text.

**What is the expected behavior?**
The textable component should be dropped inside the text area at the cursor position.

**What is the current behavior?**
The textable component is dropped outside of the text area.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harsh201** [comment]
@artf I am also facing same issue. Any suggestions here?
