### ISSUE TITLE
BUG: Updating to GrapesJS v19.5 from v18.4 results in Chrome becoming unresponsive

### ISSUE THREAD

**Issue by benryanwilliams** [GrapesJS/grapesjs#4497]
### GrapesJS version

- [x] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 104.0.5112.79

### Reproducible demo link

https://jsfiddle.net/gvrnw2c3/4/

### Describe the bug

**How to reproduce the bug?**

I'm currently unable to reproduce the bug using jsfiddle, which leads me to believe it's a problem with Chrome, but I'll continue trying to reproduce this.

_Within my project as shown in the video:_

1) Click on a 'conditional-text' component (custom component type I've added) 
2) Click on 'Open Conditionals' button then within the dialog that appears on the screen, click 'Apply'
3) Hover the cursor over the 'conditional-text' component

_In JSFiddle (currently doesn't crash but I will continue to test):_

1) Click on the 'Hello World' text component
2) Click on the 'Convert to Conditional' button at the bottom of the page
3) Click on the newly created 'conditional-text' component (with the text "Open conditionals to choose text")
4) Click on the 'Change Conditional' button at the bottom of the page
5) Move the cursor over the 'conditional-text' component (currently doesn't crash but I will continue to test)

**What is the expected behavior?**

The app should continue running as normal (works fine in GrapesJS v18.4)

**What is the current behavior?**

The whole screen crashes as soon as the cursor is over the 'conditional-text' component and after around 5 seconds the following appears:

<img width="455" alt="Screenshot 2022-08-03 at 18 15 14" src="https://user-images.githubusercontent.com/67364267/182594957-2cc8e70b-42c4-452e-b29e-b02d77e9821c.png">

Here is the screen capture of the issue:

https://user-images.githubusercontent.com/67364267/182598233-29209c1b-b99e-438c-9d9a-3e46dd750a31.mov

**After some (unsuccessful) debugging, I also found the following:** 

The **commented out** lines in the following methods (which are triggered upon clicking the 'Apply' button as seen in the video) seemed to be responsible for the crash. It's worth mentioning that all of these lines, when not commented out, affect the appearance of the component in the canvas (i.e. they change the visible text), so perhaps it's something to do with the view of the component being rendered. The other lines below do not result in the crash :

```
applyIfCondition(conditionCode, conditionObjects) {
      const selectedComponent = this.editor.getSelected()
      if (selectedComponent.isInstanceOf("conditional-text")) {
        console.log(conditionCode, ...conditionObjects)
        selectedComponent.addAttributes({ liquidtag: "if" })
        // selectedComponent.components(conditionCode)
        selectedComponent.set("conditionObjects", conditionObjects)
        selectedComponent.set("isNew", false)
        // selectedComponent.getView().render()
      }
    },
    selectIfCondition(displayText, selectedIndex) {
      const selectedComponent = this.editor.getSelected()
      if (selectedComponent.isInstanceOf("conditional-text")) {
        console.log(displayText, selectedIndex)
        // selectedComponent.set("displayedText", displayText)
        selectedComponent.set("selectedConditionIndex", selectedIndex)
        // selectedComponent.getView().render()
      }
    },
```

So it's the following lines that seem to cause the crash, from what I can tell so far - if I uncomment any of these lines from the methods, the text inside the component changes upon clicking apply and the crash happens when hovering over the component :

`selectedComponent.components(conditionCode)`
`selectedComponent.getView().render()`
`selectedComponent.set("displayedText", displayText)`
`selectedComponent.getView().render()`

_N.B. The custom 'conditional-text' component in my project is the same as in the jsfiddle - I have tried to reproduce the error by simplifying the rest of the code (I didn't want to copy over all of the logic from my project), but the code that matters is still being executed._

Please let me know if you require any further information.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by benryanwilliams** [comment]
I've since reproduced the issue with a much more simplified version of the project - the layout and styling of the editor in this example is all over the place but should still function normally. By the way, I'm using Vue 3 but this shouldn't affect the functionality - as previously mentioned everything works fine when using GrapesJS v18.4 (it's only when updating to 19.5 that the issue occurs). Hopefully you can reproduce the issue inside a normal JS project.

Here's the code:

```
<template>
  <div class="flex items-stretch justify-start editor-row flex-nowrap">
    <div class="flex-grow editor-canvas">
      <div id="gjs"></div>
    </div>
    <div class="relative w-56 max-h-screen overflow-scroll panel__right">
      <div class="blocks-container" id="blocks-container"></div>
    </div>
  </div>

  <button @click="convertToConditional">Convert to Conditional</button>
</template>

<script>
import grapesjs from "grapesjs"
import "grapesjs/dist/css/grapes.min.css"
import "grapesjs/dist/grapes.min.js"

export default {
  data() {
    return {
      editor: null,
    }
  },
  methods: {
    convertToConditional() {
      const component = this.editor.getSelected()
      var styles = component.getStyle() || {}
      const coll = component.collection
      const at = coll.indexOf(component)
      coll.remove(component)

      const newComponent = coll.add(
        {
          type: "conditional-text",
        },
        { at }
      )

      newComponent.setStyle(styles)
    },
  },
  mounted() {
    this.editor = grapesjs.init({
      container: "#gjs",
      fromElement: 1,
      height: "100%",
      storageManager: { type: 0 },
      plugins: ["gjs-blocks-basic"],
      blockManager: {
        appendTo: ".blocks-container",
      },
    })

    this.editor.DomComponents.addType("conditional-text", {
      extend: "text",
      isComponent: (el) => el.tagName == "CONDITIONAL",
      model: {
        defaults: {
          tagName: "conditional",
          displayedText: "Open conditionals to choose text",
          conditionObjects: [],
          selectedConditionIndex: -1,
          isNew: true,
        },
      },
      view: {
        init() {
          this.listenTo(this.model, "change:displayedText", this.render)
        },
        onRender() {
          this.el.innerHTML = this.model.get("displayedText")
        },
      },
    })
  },
}
</script>

<style>
.gjs-cv-canvas {
  top: 0;
  width: 100%;
  height: 100%;
}
</style>
```

**Steps to reproduce the issue:** 

1) Add a column to the canvas
2) Add a text component below this column
3) Select the text component then click the 'Convert to Conditional' button at the bottom
4) Move the cursor around - you can see that it works fine until you hover over the conditional text component, and then it freezes.

**Video showing correct behaviour with GrapesJS v18.4**

https://user-images.githubusercontent.com/67364267/182761708-b98911ec-22a6-44c2-a112-fd80c52701ec.mov

**Video showing incorrect behaviour with GrapesJS v19.5**

https://user-images.githubusercontent.com/67364267/182762291-8155c88f-a11b-4dd0-8df9-06aef601c1ff.mov

**Comment by artf** [comment]
Sorry @benryanwilliams I've tried to reproduce it but I'm not able 🙁
By looking at the behavior in your videos it looks like it's stuck in some kind of loop when you hover that component, but I'm not sure which might be the reason. 
* Is it happening to you in other browsers?
* By checking v0.19.* updates the only impactful thing that I can think of is the switch to the Standard mode for iframes. 
   Try to check if rolling back to the previous mode has any impact
   ```js
   grapesjs.init({
     // ...
     canvas: {
        frameContent: '',
      },
   })
   ```
* Try to pause your JS execution in the devtools when the app starts being unresponsive, it should bring you inside the incriminate loop.
![Schermata 2022-08-04 alle 12 39 34](https://user-images.githubusercontent.com/11614725/182827839-569cae7f-7831-456f-9514-e30e42599b7b.png)

**Comment by benryanwilliams** [comment]
Hi @artf - thanks for trying anyway. Please see my answers below:

> _1. Is it happening to you in other browsers?_ 

Yes, I confirm that I'm seeing the same behaviour inside Safari also

> _2. By checking v0.19.* updates the only impactful thing that I can think of is the switch to the Standard mode for iframes.
> Try to check if rolling back to the previous mode has any impact_

I've tried applying the canvas frameContent adjustment that you suggested but I still get a crash

> _3. Try to pause your JS execution in the devtools when the app starts being unresponsive, it should bring you inside the incriminate loop._

Unfortunately, of all the place for it to take me to when pausing, it's taken me to this very long line of code within grapes.min.js, so I'm not really sure how to look into this further! Is there anything else that I can do to find out where inside grapes.min.js it's crashing?

<img width="1440" alt="Screenshot 2022-08-05 at 18 30 51" src="https://user-images.githubusercontent.com/67364267/183068741-e8653910-c636-4945-84ad-91cf5471233a.png">

**Comment by artf** [comment]
> Unfortunately, of all the place for it to take me to when pausing, it's taken me to this very long line of code within grapes.min.js, so I'm not really sure how to look into this further! Is there anything else that I can do to find out where inside grapes.min.js it's crashing?

You should allow the devtool to read the sourcemap of grapesjs (included in the bundle) so you can view the source.

**Comment by benryanwilliams** [comment]
Thanks @artf - I've done this but it loops through so many different files so it's hard to find where exactly it happens (Chrome becomes unresponsive but doesn't display the error message while debugging this way for some reason, it presumably just continues to loop).

Not sure whether this helps (perhaps the recursion is expected) but this is the call stack after hovering:

https://user-images.githubusercontent.com/67364267/183117275-d887e827-c76e-405f-b1dc-b08c4610fdaa.mov

It also ends up on this at some point during the loop, again unsure whether relevant:

<img width="992" alt="Screenshot 2022-08-05 at 22 32 33" src="https://user-images.githubusercontent.com/67364267/183111105-8137a1cc-8747-47a1-9d6c-3a26de844486.png">

It also seems to be jumping between Vue files and grapes.min.js as follows (had to do it very fast so that the file is lower than 10MB but hopefully you can pause the video to see the various steps:

https://user-images.githubusercontent.com/67364267/183120476-0f75f28f-9c89-4a00-928f-1b21edd496cf.mov

Is there any way for me to send you a full log or for you to help remotely please? I'm quite new to all of this, especially trying to combine Vue and GrapesJS. It just seems weird that it works with the previous version of GrapesJS.

for the meantime I'll continue working on version 18.4 anyway, but if there's anything else I can provide then please let me know.

**Comment by tyutony** [comment]
A reproduce on Fiddle (with vue)
I can not reproduce  without vue
[jsfiddle](https://jsfiddle.net/6qp48xyn/)


**Steps to reproduce the issue:**
1. Add a text component below this column
2. Select the text component then click the 'Convert to Conditional' button at the bottom
3. Hover over the conditional text component, and then it freezes.

Seems something just trigger onHover forever
![image](https://user-images.githubusercontent.com/30591406/184062993-73d84ef7-0c07-4832-bd7b-9ac6d3851a5d.png)
![image](https://user-images.githubusercontent.com/30591406/184063004-9372e05b-7cb0-4ed7-931c-28225de92c4d.png)

**Comment by benryanwilliams** [comment]
Thanks for doing this @tyutony - not sure why I didn't think of adding Vue inside jsfiddle. Just to reiterate @artf, this doesn't happen in v18.4, hopefully you can test your end and find out why this is happening. Thanks both!

**Comment by artf** [comment]
Thanks guys, I was actually able to reproduce it by wrapping the example inside Vue but I'm not sure exactly why is stuck in the loop here. 
At first look, it seems to be related to Vue's Proxy observers. By comparing the demo with the previous grapesjs version it looks like not all parts are transformed in Proxies and that prevents it from being stuck.
As a quick workaround here would be to put the `editor` outside of Vue to prevent transforming all objects into proxies.
```js
let editor;
Vue.createApp({
 mounted() {
   editor = grapesjs.init({ ... });
    // ...
  },
 // ..
}).mount('#app')
```

**Comment by benryanwilliams** [comment]
Thanks @artf, all working perfectly now upon declaring the editor outside of the Vue instance.

**Comment by renalpha** [comment]
Came across this.

let grape = toRaw(pagebuilder.GrapesJS);

This allows you to bypass proxys
