### ISSUE TITLE
Grapesjs goes out of memory Issue

### ISSUE THREAD

**Issue by DhanaDSP1120** [GrapesJS/grapesjs#4558]
While apply bold ,italic, underline continuously to a text . when once opened layer manager only its happened And
its works fine only in V0.18.2 and its below 

Reproduce links

Working version :
https://jsfiddle.net/76gnxh4d/39/

Not working version :
https://jsfiddle.net/76gnxh4d/40/

Demo :
![grapesjs version issue 2](https://user-images.githubusercontent.com/54067384/188277178-5cd2021d-5070-411f-9b71-ae339f64c5d6.gif)

_Originally posted by @DhanaDSP1120 in https://github.com/artf/grapesjs/discussions/4550_

**Comment by DhanaDSP1120** [comment]
@artf Issue was not solved

**Comment by artf** [comment]
@DhanaDSP1120 looks like a stress edge case nobody really cares, but if you want to dig into the fix, I'll be open to merge a PR
