### ISSUE TITLE
BUG: setStyle/getCss() produces duplicated css

### ISSUE THREAD

**Issue by handhikadj** [GrapesJS/grapesjs#4900]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Latest

### Reproducible demo link

https://codesandbox.io/s/silent-river-ifczcv

### Describe the bug

**How to reproduce the bug?**
1. Visit the site
2. See console. Pay attention to the `*` and `body` selector

**Expected result**
Should not be duplicated

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
editor = grapesjs.init({ 
    storageManager: false
    // ...
    })

editor.on("update", () => {
        // save to backend
        console.log("editor getCSs", editor.getCss());
      });

      editor.on("load", () => {
        // this will come from backend
        const style = "* { box-sizing: border-box; } body {margin: 0;}";
        
        editor.setStyle(style);
        
        // const html = backendHtml (<body><div></div></body>)
        // editor.setComponents(html)
      });
```

**Description**

I do this because the new storageManager mechanism/schema destroys my entire app, especially the backend stuff.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
There are  default styles applied that you can simply disable (pass an empty string) https://github.com/GrapesJS/grapesjs/blob/a83847b1b35e69e5a5810ccf1eb1e1384bf0aab1/src/editor/config/config.ts#L143-L147
