### ISSUE TITLE
BUG: getHtml() producing invalid structure when there is js inside it

### ISSUE THREAD

**Issue by handhikadj** [GrapesJS/grapesjs#4904]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome latest

### Reproducible demo link

https://jsfiddle.net/snj87o6f/1/

### Describe the bug

**Context/Description**
I think this is a bug because I need to save and load the data back with editor.Parser.parseHtml on onStore of storageManager. it's even worse, the structure on the Layer Manager is broken when I refresh the page (onLoad runs). seems like editor.Parser.parseHtml() doesn't parse it correctly

**How to reproduce the bug?**
1. drag and drop the countdown block to canvas
2. see the console

**What is the expected behavior?**
should produce valid html even if there is js inside it so that it's good on storageManager.options.remote.onLoad() and Layer Manager (I think)

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
allowScripts: true,
options: {
                            remote: {
                                urlStore: `${baseUri}/storeBuilderHtmlData`,
                                onStore: (storeData, gEditor) => {
                                    return {
                                        pageId,
                                        'gjs-css': gEditor.getCss(),
                                        'gjs-html': gEditor.getHtml(),
                                    }
                                },
                                urlLoad: `${baseUri}/loadBuilderHtmlData?pageId=${pageId}`,
                                onLoad: async (result, gEditor) => {
                                    const { Parser } = gEditor;
                                    const gData = { ...result };

                                    if (!gData.pages) {
                                        gData.pages = [
                                            {
                                                component: Parser.parseHtml(gData.html)['html'],
                                            },
                                        ];
                                    }

                                    if (!gData.styles) {
                                        gData.styles = gData.css ? Parser.parseCss(gData.css) : undefined;
                                    }

                                    delete gData.css;
                                    delete gData.html;

                                    gData['assets'] = myImageAssets;

                                    return gData;
                                }
                            }
                        }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
The output is correct (check the real console not the broken one from jsfiddle) and read carefully [this section](https://grapesjs.com/docs/modules/Storage.html#project-data), you should never rely on HTML/CSS to load back the project.
