### ISSUE TITLE
BUG: Grapesjs fails to recognize component types when setting innerHTML through script.

### ISSUE THREAD

**Issue by panditlakshya** [GrapesJS/grapesjs#4906]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome  v108.0.5359.98 

### Reproducible demo link

https://codesandbox.io/s/grapes-js-template-literal-forked-6kgvrb?file=/src/App.js

### Describe the bug

I'm trying to create a custom component that recognizes inner html component types after injecting html code through script.

**How to reproduce the bug?**
1. Just inject the html through script 

```
const el = this;
el.innerHTML = `<div data-gjs-resizable="true" data-gjs-layerable="true" data-gjs-draggable="true" data-gjs-selectable="true" data-gjs-hoverable="true">
<img data-gjs-resizable="true" data-gjs-layerable="true" data-gjs-draggable="true" data-gjs-selectable="true" data-gjs-hoverable="true" src="" alt="">
<h5 data-gjs-resizable="true" data-gjs-layerable="true" data-gjs-draggable="true" data-gjs-selectable="true" data-gjs-hoverable="true">Lakshya</h5>
<h6 data-gjs-resizable="true" data-gjs-layerable="true" data-gjs-draggable="true" data-gjs-selectable="true" data-gjs-hoverable="true">Artist</h6>
</div>`;
```

**What is the expected behavior?**
Canvas should be able to recognize component types like text, image, etc  after injecting code. 

**What is the current behavior?**
Injected part is recognized as text component as whole.(Injected code may contain div element with image or text)

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Read carefully [this guide](https://grapesjs.com/docs/modules/Components-js.html), everything inside `script` is outside of the editor scope. You can update the component itself by using [component.components](https://grapesjs.com/docs/api/component.html#components) method or specify the `components: '<div ....'` directly in definition.
