### ISSUE TITLE
BUG: broken links in the docs

### ISSUE THREAD

**Issue by lexoyo** [GrapesJS/grapesjs#4912]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

any

### Reproducible demo link

no

### Describe the bug

Since the move from artf to GrapesJS I believe many links are still to the original repo
https://github.com/GrapesJS/grapesjs/search?q=artf

Should I try to replace it or do we trust github redirects?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
I think some stuff are redirecting but others might be broken, I'd appreciate a PR if anyone is willing to help 🙏

**Comment by lexoyo** [comment]
I did a PR, I hope I didn't miss anything, I had to test almost each link
