### ISSUE TITLE
BUG: calling destroy method breaks the editor ( React app )

### ISSUE THREAD

**Issue by maliuta-oleksandr** [GrapesJS/grapesjs#4919]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 109.0.5414.119

### Reproducible demo link

-

### Describe the bug

**How to reproduce the bug?**
1. add event listener to outside click
2. call destroy method

**What is the expected behavior?**
- Destroying without errors

**What is the current behavior?**
Parser is undefined, but it tries to call its method.
**Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parseHtml')**
Callstack:
```
n.parseString (Components.ts:225:1)
    at n.resetFromString (Components.ts:107:1)
    at n.syncContent (ComponentTextView.ts:150:1)
    at n.<anonymous> (ComponentTextView.ts:122:1)
    at ComponentLink.ts:44:1
    at Object.next (ComponentLink.ts:44:1)
    at s (ComponentLink.ts:44:1)
```

```
document.addEventListener('click', function (event) {
            var $target = event.target;
            if($el &&  editorReady.current && !$target?.closest(`#${id}`)?.length) {
                editorRef?.current?.destroy();
            }
        });
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Are you able to provide a reproducible demo as I'm not able to reproduce it on my end?
