### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by soubverified** [GrapesJS/grapesjs#4921]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Version 110.0.5481.78 (Official Build) (64-bit)

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Install GrapesJs with npm or CDN and initialize as usual to a container e.g. div with id #something..
2.  On the console , check if verbose level is set to active.
3. After everything is set , and the page is loaded . Refresh the page and watch for console logs . 

**What is the expected behavior?**
well , the verbose messages should be fixed. 

**What is the current behavior?**

Shows more than 60 verbose messages currently.
![Screenshot 2023-02-08 213625](https://user-images.githubusercontent.com/107591128/217587078-499df098-3724-40b1-a0cd-c311a01ead10.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Closing as this is not related to the core but to the [demo page](https://github.com/GrapesJS/grapesjs/blob/gh-pages/demo.html), please make a PR if you want to suppress those warnings
