### ISSUE TITLE
BUG: Using !important code provided here breaks background image and gradient.

### ISSUE THREAD

**Issue by clonefunnels** [GrapesJS/grapesjs#4922]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox

### Reproducible demo link

https://jsfiddle.net/jLgb0mv3/1/

### Describe the bug

**How to reproduce the bug?**
1. ...Put this code in the editor:
 
editor.on('styleable:change', (model, property) => {
const value = model.getStyle()[property];
if (value.indexOf('!important') === -1) {
model.addStyle({ [property]: value + ' !important' });
}
});

2. Try to set a background image or gradient.

**What is the expected behavior?**
It should let you set a background image or gradient.

**What is the current behavior?**
It doesn't.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```
const editor = grapesjs.init({
	container: '#gjs',
  fromElement: 1,
  height: '100%',
  storageManager: { type: 0 },
  plugins: ['gjs-blocks-basic']
});
editor.on('styleable:change', (model, property) => {
const value = model.getStyle()[property];
if (value.indexOf('!important') === -1) {
model.addStyle({ [property]: value + ' !important' });
}
});

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
I only see the issue with `composite`/`stack` style manager properties and that is because not every style manager property is part of the styles so in your code you would only need to check if the value of the style actually exists, eg. `if (value && value.indexOf('!important') === -1) {...`
