### ISSUE TITLE
BUG: block:custom is not working on React

### ISSUE THREAD

**Issue by besart-k** [GrapesJS/grapesjs#4937]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Version 110.0.5481.100 (Official Build) (arm64)

### Reproducible demo link

None

### Describe the bug

I am trying to replicate in React the customizing the Block Manager like in this example  [Vue block manager](https://jsfiddle.net/artur_arseniev/xyofm1qr/), but the "block:custom" callback is not called.

**How to reproduce the bug?**
Put this on init configuration
`blockManager: {
          blocks: blocks,
          custom: true
  },`

Put this on inside useEffect
`
useEffect(()=>{
editor.on('block:custom', (props)=>{console.log(props)})
},[])
`
 
**What is the expected behavior?**
props needs to shown on console log like in Vue example

**What is the current behavior?**
callback of block:custom is not called

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@besart-k you have to provide a reproducible demo as if it works with the current Vue demo example it shouldn't be different in React. Maybe you're using an old version of grapesjs or doing something wrong in your React app, so in this case the reproducible demo is mandatory.
I'm closing this one as the demo itself uses the latest version it seems to work properly for custom blocks.
