### ISSUE TITLE
BUG: Destroying and re-initializing produces "Cannot read properties of undefined (reading 'get')"

### ISSUE THREAD

**Issue by mani-rai** [GrapesJS/grapesjs#4940]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Google Chrome Version 110.0.5481.100 (Official Build) (64-bit)

### Reproducible demo link

https://stackblitz.com/edit/js-3urscf?file=index.html,index.js

### Describe the bug

**How to reproduce the bug?**
1. Initialize the editor
2. Destroy the editor
3. Initialize the editor again

**What is the expected behavior?**
The code used is just a starter code from the official doc. It should be re-initialized without any problem.

**What is the current behavior?**
Multiple errors are show in console.

> TypeError: Cannot read properties of undefined (reading 'get')
    at o.runDefault (Editor.ts:874:28)
    at n.updateOffset (FrameWrapView.ts:89:8)
    at _e (_executeBound.js:8:65)
    at n.eval (bind.js:10:12)
    at n.eval (restArguments.js:16:27)
    at l (debounce.js:17:37)

Another:

> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
    at s (Editor.ts:317:20)
    at o.eval (Editor.ts:336:9)
    at eval (grapes.min.js:2:911116)
    at Object.eval [as next] (grapes.min.js:2:911221)
    at eval (grapes.min.js:2:910096)
    at new Promise (<anonymous>)
    at nh (grapes.min.js:2:909838)
    at eval (Editor.ts:326:18)

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// Not Necessary
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Yeah, the editor instance is not expected to be destroyed immediately due to some timed async functions (eg. for the StorageManager) but that can be fixed.
For now you can overcome the issue by doing something like this:
```js
setTimeout(() => {
  editor.destroy();
  ...
```
