### ISSUE TITLE
BUG: Undo manager not working properly on undoing a remove action

### ISSUE THREAD

**Issue by FaisalShaikhHA** [GrapesJS/grapesjs#4947]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome - version 110.0.5481.100 (Official Build) (arm64)

### Reproducible demo link

https://codepen.io/faisal-praella/pen/ExeNwxJ

### Describe the bug

- I have added a custom **columns** component with a number trait name **columns** used for adding or removing the child component column.
- When I add a new column using the trait and undo the change it works fine but when I remove the column and undo the change an extra column is added.
- This might be because when Grapesjs undo remove change it appends the removed column and reverts the column trait as well, but this column trait change triggers `this.listenTo(this, "change:columns", this.updateColumns);` which adds the new column as well. If this is the case then how to avoid listening to the column trait change on undo or when undoing the removed change Grapesjs should append the removed element first and then revert all other property/trait changes (undo in reverse order) or any other way to handle this situation?

**What is the expected behavior?**
No extra column should be added on undoing the remove action.

**What is the current behavior?**
An extra column is added on undoing the remove action.

https://user-images.githubusercontent.com/102785785/221497088-11a9ddf6-b083-4a15-98ad-694664b967ea.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Yeah undo triggers the `change:columns`, in your case you could try to wrap your `updateColumns` changes in `editor.UndoManager.skip`.
```js
updateColumns() {
  editor.UndoManager.skip(() => {
    // your operations
  })
}
```

**Comment by FaisalShaikhHA** [comment]
Thank you @artf it works, to fix this I was toggling the trait change listener by listening to undo command run events but this feels cleaner. 
The checkbox trait not getting checked or unchecked on undo/redo (trait value is updated on my end). Reproducible on Grapesjs webpage [demo](https://grapesjs.com/demo.html). Need help here as well thank you once again.

https://user-images.githubusercontent.com/102785785/224402423-fd04268a-8969-46ae-8a34-6d249493ecaf.mp4

**Comment by artf** [comment]
Ok I'm closing this one then and please open a new bug issue related to checkbox traits.
