### ISSUE TITLE
BUG: new storage doesn't work

### ISSUE THREAD

**Issue by wyxcoder** [GrapesJS/grapesjs#4967]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://jsfiddle.net/1vknjLst/

### Describe the bug

**How to reproduce the bug?**
click run

**What is the expected behavior?**
load and save in the new storage should be called and console should display "loading"

**What is the current behavior?**
nothing happens

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
1. You have to use the plugin `plugins: [dbStoragePlugin, 'gjs-blocks-basic']`
2. With `autosave: false` you're disabling the autosave, which means the `Storage.store` will be triggered only if called programatically (eg. `editor.store()`)
3. There is no `setStepsBeforeSave` option but `stepsBeforeSave`

**Comment by wyxcoder** [comment]
thank you! that works fine
