### ISSUE TITLE
BUG: slow absolute drag on Chrome

### ISSUE THREAD

**Issue by ngoc199** [GrapesJS/grapesjs#5003]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 111

### Reproducible demo link

https://jsfiddle.net/9zf4kd6e/ - this is the demo of Designer Mode

### Describe the bug

**How to reproduce the bug?**
1. Add an image component with `dragMode` absolute
2. Upload a large enough SVG image. You can use [this image](https://freesvg.org/anime-girl-warrior)
3. Drag the image around
4. Drag the text component around

**What is the expected behavior?**
- The SVG image is not resized on drag
- The SVG image is moved fast to the right position
- The components are moved fast when there is a large SVG image

**What is the current behavior?**
- The SVG image is automatically resized on drag following the cursor position. After manually resizing the image, it can be dragged without being resized.
- The SVG image is moved slowly.
- The other components are moved slowly when there is a large SVG image.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@ngoc199 I'm addressing most of the issue about absolute mode [here](https://github.com/GrapesJS/grapesjs/issues/3770#issuecomment-944915841). I think the resize issue could be easily added here but the large embedded SVG image (by default, without an external asset storage, images are inlined) it's seems more like a browser limit
