### ISSUE TITLE
BUG: Changing Title Attribute on Views Panel Buttons Doesn't Persist

### ISSUE THREAD

**Issue by at-codes** [GrapesJS/grapesjs#5020]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://jsfiddle.net/em9kt2Lb/

### Describe the bug

**How to reproduce the bug?**
Implement the code below on editor load

**What is the expected behavior?**
Button titles change and stay changed

**What is the current behavior?**
Button titles change, but after clicking one of them it reverts back. 

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
    // Change the title of the view buttons
    let view_buttons  = $('.gjs-pn-views > .gjs-pn-buttons').find('span');

    view_buttons.each(function( index, elem ) {
        switch ($(elem).attr('title')) {
            case 'Open Style Manager':
                $(elem).attr('title', 'Styling');
                $(elem).prop('title', 'Styling');
                break;
            case 'Open Layer Manager':
                $(elem).attr('title', 'Layer Manager');
                $(elem).prop('title', 'Layer Manager');
                break;
            case 'Open Blocks':
                $(elem).attr('title', 'Page Layout');
                $(elem).prop('title', 'Page Layout');
                break;
            default:
                break;
        }
    });
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Hi @at-codes titles for panel buttons are connected directly to [i18n locale strings](https://github.com/GrapesJS/grapesjs/blob/976e791c5abd6f876a0f29b58de32ff1549f32c2/src/i18n/locale/en.js#L48) so you'll need to update those strings there. You can find more info about the i18n module [here](https://grapesjs.com/docs/modules/I18n.html).
