### ISSUE TITLE
FEATURE: How to drag external text into particular index inside the textable component?

### ISSUE THREAD

**Issue by siddhi1397** [GrapesJS/grapesjs#5037]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

NA

### Describe the bug

**How to reproduce the bug?**
1. ...
2. ...

**What is the expected behavior?**
... When I drag external content inside the editor it should be dropped at specific position 

**What is the current behavior?**
... It is getting dropped at the position but it is overlapping the text that is already present in the component

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by siddhi1397** [comment]
Hi @artf ,
When I drag external content inside the editor it should be dropped at specific position but it is overlapping the existing content in the component. So is there any way where I can place text at the specific position without getting overlapped?

FYI, I am using canvas:dragdata for the getting the external content.

**Comment by artf** [comment]
Please provide at least a reproducible demo so it's possible to understand what you're talking about

**Comment by siddhi1397** [comment]
[screencast-localhost_4200-2023.04.11-15_22_42.webm](https://user-images.githubusercontent.com/121800257/231125084-d36d3a2d-653c-4769-bf81-e38d844e37f8.webm)
@artf , So here my requirement is to drop that external text between words like Insert your text here or say any text like that but I am unable to do so as I am unable to grab position of external text inside it.
So is there any way where we can drag and drop external text between words inside canvas at specific position?

**Comment by siddhi1397** [comment]
@artf let me know if you need more detail on the requirement.

**Comment by siddhi1397** [comment]
Hi @artf ,
Can you please check the scenario now?

**Comment by artf** [comment]
You can have textable components/blocks ([example](https://jsfiddle.net/artur_arseniev/0b9ox72g/)) but currently applying the same on external components is not supported.

**Comment by siddhi1397** [comment]
Thank you for the update! @artf
