### ISSUE TITLE
BUG: Every time editor.loadData(data, opts) is called, it triggers the store method defined in editor.Storage.add("api-remote", {...}), which logs the message 'api-remote store'

### ISSUE THREAD

**Issue by pittleCheung** [GrapesJS/grapesjs#5042]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

latest version of Chrome

### Reproducible demo link

null

### Describe the bug

**How to reproduce the bug?**
it's easy

**What is the expected behavior?**
I want to use editor.load to load data and switch pages, but I don't want editor.Storage to be called every time.

**What is the current behavior?**
"Every time editor.loadData(data, opts) is called, it triggers the store method defined in editor.Storage.add("api-remote", {...}), which logs the message 'api-remote store'."

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
export function apiRemoteStoragePlugin(editor: any, opts: any = {}) {
  // @ts-ignore
  editor.Storage.add("api-remote", {
    async load() {
      const { pid, sid } = opts;
      let rep = await $http.get(`/site-pages/${pid}`);

      if (rep?.siteId != sid) {
        throw new Error("页面不存在");
      }

      console.log("resp=====", pid, sid);

      return getProjectDataByQueryData(rep);
    },
    async store(data: any) {
      const { pid, sid } = opts;
      alert(pid, "===", sid);
      // await $http.patch(`/site-pages/${pid}`, {
      //   data
      // });
      return data;
    }
  });
}

editor.loadData(data, opts) 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You can update dynamically `stepsBeforeSave` in order to avoid triggering the store on Storage call. 
Please next time use Discussions as this is not a bug but implementation question.
