### ISSUE TITLE
BUG: is there any way to remove cross svg on selected default value of Float, Position and text-align

### ISSUE THREAD

**Issue by Spiral1234** [GrapesJS/grapesjs#5046]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 111.0.5563.147 (Official Build) (64-bit)

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
this is the image link where you can check
https://ibb.co/0Qg7nTK

**What is the expected behavior?**
the cross icon should be removed when we click on default values if we select float with a value of none then the cross icon should display non

**What is the current behavior?**
Current behavior cross icon is not removed on select default value

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@Spiral1234 there is a big difference between a default value and the defined one (even if it's the same as default). For example on desktop you define `float: right` and on mobile `float: none`, you still need the possibility on mobile to remove the `none` value.

**Comment by Spiral1234** [comment]
@artf, let me define you one more time.
My question is that if I click on the default value of any module like for float I select ``none`` then ``cross svg`` should be ``display: none`` same as I want for others ``position``, ``text-align``

if someone will select default value then above ``cross svg`` which is coming for reset should be ``display: none``

I put a screenshot in which I mentioned cross svg for reset that should be ``display: none``  on the selected default value. Thanks

**Comment by artf** [comment]
@Spiral1234 it shouldn't be `display: none` if you SELECT the default value, try to read carefully again the use case explained above, having the default value and selected one is DIFFERENT.
