### ISSUE TITLE
Styles loaded through vue entry point not working

### ISSUE THREAD

**Issue by innothetechgeek** [GrapesJS/grapesjs#5052]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

N/A

### Describe the bug

I'm integrating the grape.js plugin with vue.js. I have a prebuild page with prebuild html and css.

When I load the page vue.js component(s) into the editor, all my vue.js styles get lost. but if I remove the grapeJs init method my styles are working fine.

please help. I want to load the styles loaded through the vue.js entry point into the editor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@innothetechgeek for a proper bug issue you should always create a reproducible demo as commonly there are issues unrelated to the core itself. Anyway, from your description you might want to define your styles entry via [`canvas` options](https://grapesjs.com/docs/modules/Components-js.html#template-related)
