### ISSUE TITLE
BUG: types are changed to `any` in v0.21.1

### ISSUE THREAD

**Issue by ngoc199** [GrapesJS/grapesjs#5053]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

FireFox 112.0 (64-bit)

### Reproducible demo link

No demo link

### Describe the bug

I recently upgraded from v0.20.1 to v0.21.1.

A lot of types that existed in v0.20.1 are changed to `any` in v0.21.1.

For example,

**Type of `Components.addType` in v0.20.1 is `AddComponentOptions`**

![image](https://user-images.githubusercontent.com/53241275/232444631-243b6872-1655-490b-b5b4-5c5ad546a315.png)

**Type `Components` is changed to `ComponentManager`. Type of `ComponentManager.addType` in v0.21.1 is `any`**

![image](https://user-images.githubusercontent.com/53241275/232446328-3f6cbac3-e7a4-4549-83fa-20686d86a0ae.png)

**How to reproduce the bug?**
1. Install the latest version of GrapesJS
2. Add a custom type
3. Get errors about `any` type

**What is the expected behavior?**
The types are defined as the previous version, not `any`.

**What is the current behavior?**
The types are defined as `any`.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```ts
  const domc = editor.DomComponents;
  const blockManager = editor.BlockManager;

  // This type is defined
  blockManager.add("section", sectionBlock);

  domc.addType("section", {
      // `isComponent` and `el` are `any`
    isComponent: function (el) {
      return el && el.classList && el.classList.contains("section");
    },

    // `model` is `any`
    model: {
        init() {
            // `this` is bind to this object, which has only `isComponent` and `model`
            // `on` does not exist
            this.on("change:attributes", () => {})
        }
    }
  )
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @ngoc199 please let me know if there are others missing declarations from the previous versions
