### ISSUE TITLE
BUG: on second-time use template grapes editor not accepting css which the editor created with random ids on the first time

### ISSUE THREAD

**Issue by Spiral1234** [GrapesJS/grapesjs#5059]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 111.0.5563.147 (Official Build) (64-bit)

### Reproducible demo link

I can't Reproducible on jsfilddle. i provided detail below.

### Describe the bug

**How to reproduce the bug?**
1. This is my template which I uploaded in Grapes in which I have inline CSS in a style tag in the head as well as an inline style in body tags
https://jsfiddle.net/spiral417/udye5ov1/
2. First-time Grapesjs fetched inline CSS from body tags and insert random ids and put CSS in these ids. so I'm saving all CSS styles but when I use this same template a second time and setStyle which grapes provided then grapes is not accepting this style which it created the first time with random ids only accepting head style CSS which is properly with the class so due to this on second-time style is not implementing

I provided also the link in which grapes js created CSS style with random ids which are not accepting on settle on the second time
https://jsfiddle.net/spiral417/uo8fLba5/1/

**What is the expected behavior?**
The expected behavior is that the grapes js editor should accept and should setStyle on the second time also which it created the first time with random ids

**What is the current behavior?**
The current behavior is that the grapes js editor is not accepting CSS style with random ids which it created the first time

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@Spiral1234 if you're not able to reproduce the issue it's probably something on your end and without a reproducible demo it's hard to understand what might be a problem
