### ISSUE TITLE
BUG: Crash when dragging into nested components with Vue+Vite.

### ISSUE THREAD

**Issue by TO-JHummel** [GrapesJS/grapesjs#5079]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox 112.0.2 (64-Bit)

### Reproducible demo link

https://github.com/TO-JHummel/grapesjs-issue

### Describe the bug

**How to reproduce the bug?**
1. Start the minimal vue+vite page.
2. Drop the capitalized_for block into the editor.
3. Drop the 1-column block into the editor outside of the other block.
4. Drag and drop each of the divs from the capitalized_for block into the 1-column block.

**What is the expected behavior?**
The block should simply be dropped into the column.

**What is the current behavior?**
The browser freezes up when dropping the last block.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is similar to this [one](https://github.com/GrapesJS/grapesjs/issues/4497), you have to put the editor instance outside of the Vue instance in order to bypass its proxies
