### ISSUE TITLE
BUG: Style:property:update and Property onChange trigger excessively

### ISSUE THREAD

**Issue by SagarMaria** [GrapesJS/grapesjs#5086]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Version 112.0.5615.137 (Official Build)

### Reproducible demo link

https://jsfiddle.net/SagarMaria/sunygp2f/3/

### Describe the bug

**How to reproduce the bug?**
1. In the jsfiddle simply click on the "Hello World" component. 
2. Observe the numerous console logs.
3. Click away elsewhere on the canvas, repeat.

**What is the expected behavior?**
`style:property:update` should only trigger on some style property change for the selected component

**What is the current behavior?**
`style:property:update` event is instead firing numerous times even when a component is simply selected

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// editor.on(
      'style:property:update',
      (property) => {
        console.log('property', property);
      },
    );
```

I'm looking for a way to target a the radio input change event on a custom sector in style manager. Existing documented methods don't seem to be reliable as they are firing in undesired ways.

Ideally I would like some event to detect a change in this radio button value for text align, and be able to utilize that event to add certain class names to the component, look for parents, etc:
![image](https://user-images.githubusercontent.com/83087753/235550082-1df0e5eb-5bf0-4c68-8c18-193329b1bd3f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
The behaviour is correct as `style:property:update` triggers on any update of the Style Manager [Property](https://grapesjs.com/docs/api/property.html#property) (not only its value). So for your specific case you would need to update the callback in this way
```js
editor.on('style:property:update', ({ property, to }) => {
  // Check for the property name and if the update is related to the value
  if (property.getName() === 'text-align' && to.value !== undefined) {
     console.log('text align property updated with', to.value)
  }
});
```

**Comment by SagarMaria** [comment]
Hi @artf, thanks for the quick reply, but actually, part of the problem is still that even after making a change e.g. click "center" align radio option with the if statement you suggested, subsequent selections of that component still log out `style:property:update` value with `property` and `to` set as the existing value (even if you don't change anything and just select the component). Here is a quick video below and I also updated the jsfiddle with your suggestion

https://user-images.githubusercontent.com/83087753/235668944-27e9ee52-f24f-412f-9707-c63cef4b502e.mp4
