### ISSUE TITLE
BUG: Component script function runs twice after page save

### ISSUE THREAD

**Issue by FaisalShaikhHA** [GrapesJS/grapesjs#5090]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

112.0.5615.137 (Official Build) (arm64)

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

Component definition:
```
editor.DomComponents.addType("my-test", {
        model: {
            defaults: {
                name: "Testing",
                components: "Hello testing",
                script: function () {
                    alert("hello");
                },
            },
        },
    });
```

When dropped, saved, and reload there are two places that call the same script. One in the saved HTML/JSON and one added by Grapesjs itself.

```
<script class="">
var items = document.querySelectorAll('#if1fgr');
          for (var i = 0, len = items.length; i < len; i++) {
            (function(){
alert("hello");
}.bind(items[i]))();
          }
</script>
------------------------------------------------------------------------------------------------------------------
<div data-id="if1fgr">
   <script>
        setTimeout(function() {
         var item = document.getElementById('if1fgr');
        if (!item) return;
        (function(){
     alert("hello");
     ;}.bind(item))({})
      }, 1);
   </script>
</div>
```

**How to reproduce the bug?**
1. Add a custom component type with a script function.
2. Drop it and save the page.
3. Reloading the page runs the script function twice.

**What is the expected behavior?**
The script function should be running only once.

**What is the current behavior?**
The script function runs twice.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
As explained [here](https://grapesjs.com/docs/modules/Storage.html#project-data) you should not reimport the output HTML to edit the project, only the JSON.
