### ISSUE TITLE
BUG: Adding style o component by (prop, value), isn't work correct.

### ISSUE THREAD

**Issue by Baghunts** [GrapesJS/grapesjs#5105]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome@latest

### Reproducible demo link

https://no-link.com

### Describe the bug

![image](https://github.com/GrapesJS/grapesjs/assets/133208978/3a5ce51a-fedf-4fd7-9063-a5af519690b9)
![image](https://github.com/GrapesJS/grapesjs/assets/133208978/0b990b40-94b1-48c1-94dc-c4d81adf0368)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @Baghunts, good catch. Current workaround would be `.addStyle({ 'border-left': '...' })`
