### ISSUE TITLE
BUG: When installing plugins like grapesjs basic block or tui-image-editor it is giving namespace error in node_modules.

### ISSUE THREAD

**Issue by siddhi1397** [GrapesJS/grapesjs#5107]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

NA

### Describe the bug

**How to reproduce the bug?**
1. npm install any plugin from grapesjs-basic-blocks
2. After that run the application like in my case it's angular application

**What is the expected behavior?**
It should run successfully

**What is the current behavior?**
It is giving error as namespace grapesjs not found or namespace tui-image-editor not found

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Please avoid creating bug issues if you don't have any reproducible link
