### ISSUE TITLE
BUG: GrapeJS/drag and drop not working for Brave on Linux and Wayland

### ISSUE THREAD

**Issue by putzwasser** [GrapesJS/grapesjs#5112]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 1.51.110 Chromium: 113.0.5672.77 (Offizieller Build) (64-Bit)

### Reproducible demo link

https://grapesjs.com/docs/getting-started.html#add-blocks

### Describe the bug

On Linux Wayland (Arch Linux and Gnome) using Brave you can't add blocks. If you drag and drop blocks they simply disappear after releasing the mouse button, which renders GrapeJS broken/useless.

I tried it with disabled brave shields and in incognito mode to make sure nothing interferes with the JS. Same result

**How to reproduce the bug?**
1. Open the grapejs documentation page
2. Try to add the section or text block via drag and drop
3. See that nothing happens

**What is the expected behavior?**
- The block should get added

**What is the current behavior?**
- Nothing happens

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
By checking with the same Brave version (on Mac), drag and drop seems to work properly, so it doesn't look like an issue with GrapesJS itself or the browser.
If anybody else experience the same or have more context about the issue, please let us know.

**Comment by gxanshu** [comment]
I'm facing the same issue with tauri. they use webgtk and drag & drop are not working there as well

**Comment by putzwasser** [comment]
> By checking with the same Brave version (on Mac), drag and drop seems to work properly, so it doesn't look like an issue with GrapesJS itself or the browser.

I don't feel this is a valid check. You got a completely different setup by using a Mac. I expected that this issue might be related to my specific setup, but this don't mean that there's nothing that can be done on the grapesjs side.

I'm not expecting you to fix it, as it might be a corner case and resources are tight. Maybe it's even something related to using Brave on Wayland.

**Comment by gxanshu** [comment]
> > By checking with the same Brave version (on Mac), drag and drop seems to work properly, so it doesn't look like an issue with GrapesJS itself or the browser.
> 
> I don't feel this is a valid check. You got a completely different setup by using a Mac. I expected that this issue might be related to my specific setup, but this don't mean that there's nothing that can be done on the grapesjs side.
> 
> I'm not expecting you to fix it, as it might be a corner case and resources are tight. Maybe it's even something related to using Brave on Wayland.

if thats the case then why grapesjs give's same issue in gtk2webkit on linux

**Comment by putzwasser** [comment]
> if thats the case then why grapesjs give's same issue in gtk2webkit on linux

I didn't mean exclusively related to my specific setup—this would really mean that it is my problem and I'd need to find a fix.

So, you're chiming in, is perfectly fine, as it supports this bug report.

Maybe there's an UI/desktop environment corner case that grapeJS has to handle differently. I have no clue.

**Comment by jgoclawski** [comment]
@artf 
I have the same problem with GrapesJS version 0.22.1 when using Chrome version 131 on Ubuntu 24.04 and Fedora 41, both using Wayland. Please note that his is a very typical setup, just newest Ubuntu (enabled Wayland is the default setting) with newest Chrome.
With Firefox the widgets work, even on Wayland.
I can replicate the issue in GrapesJS Studio ( https://app.grapesjs.com/studio ) and in our app which uses GrapesJS js package.

When I switch to X display server then Chrome works as well.

We used to use an older version of GrapesJS (0.14.52) and the problem wasn't here - when using Wayland both Chrome and Firefox would work correctly.

~So I think the problem is somewhere in GrapesJS after all, because things worked in an older release.~
Edit: see next comment.

**Comment by jgoclawski** [comment]
After some testing it looks like my setup was not default after all. A while ago I switched to using Chrome in native Wayland mode (by setting "Preferred Ozone platform" to "Wayland" in chrome://flags/).
With such config drag and drop doesn't work. But it looks like a browser issue.

Ref. https://github.com/hyprwm/Hyprland/issues/7496
Chromium bug: https://bugs.kde.org/show_bug.cgi?id=482142 

There's also a short blog article: https://blog.f1nley.xyz/post/web/drag-and-drop-doesnt-work-on-chrome-in-wayland/

Current workaround is to run Chrome without wayland, by setting "Preferred Ozone platform" to "X11" in chrome://flags/
Hopefully this helps anyone who finds it.
