### ISSUE TITLE
BUG: Incorrect type definition for StyleManager.addProperty

### ISSUE THREAD

**Issue by duclet** [GrapesJS/grapesjs#5135]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

All

### Reproducible demo link

None

### Describe the bug

**How to reproduce the bug?**
1. Per the definition here: https://github.com/GrapesJS/grapesjs/blob/dev/src/style_manager/index.ts#L304, you should be providing the options as `options` for `PropertyProps`.
2. However, `PropertyProps` as defined here: https://github.com/GrapesJS/grapesjs/blob/dev/src/style_manager/model/Property.ts#L9, does not have such a property. This is causing the TS compiler to complain.

**What is the expected behavior?**
Definition should exists.

**What is the current behavior?**
Definition is missing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SachinPuthiyoth** [comment]
Seems like the type definition in StyleManagerConfig.sectors is unchanged : https://github.com/GrapesJS/grapesjs/blob/5c890449a52f526bc480d6dc649ff5e01ec59140/src/style_manager/config/config.ts#L8
Shouldn't we be updating this to use PropertyTypes as in  :
https://github.com/GrapesJS/grapesjs/blob/5c890449a52f526bc480d6dc649ff5e01ec59140/src/style_manager/index.ts#L86
Shall I raise a PR for the same?
