### ISSUE TITLE
BUG: component resets attribute values on updating traits ( first time only )

### ISSUE THREAD

**Issue by rajevar** [GrapesJS/grapesjs#5141]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Version 113.0.5672.63 

### Reproducible demo link

https://jsfiddle.net/rajevar/zLs8q97f/4/

### Describe the bug

This is in reference to this discussion https://github.com/GrapesJS/grapesjs/discussions/4759

**How to reproduce the bug?**
https://jsfiddle.net/rajevar/zLs8q97f/4/
1. From the blocks, pick Text CAT:Basic component and drag to canvas.
2. HTML code after step-1   `<div class="text-primary" id="ixci">Insert your text here  </div>`
3. Update class attribute for the text component to add a new class. class-a
4. HTML code after step-3 `<div class="text-primary class-a" id="ixci">Insert your text here </div>`
5. Go to component settings and change id to text-id-1
6. HTML code after step-5   `<div id="text-id-1" class="text-primary">Insert your text here  </div>`
7. In the HTML, class-a got removed from class attribute. This happens for title change as well..
8. if the id or title changes again, the class values are preserved.
9. Repeat step-3 to add class class-b
10. Repeat step-5 to change id to 'text-id-2`
11. HTML code after step-10 `<div id="text-id-2" class="text-primary class-b">Insert your text here  </div>`

**What is the expected behavior?**
Expected html code after step-5 `<div id="text-id-1" class="text-primary class-a">Insert your text here  </div>`

**What is the current behavior?**

If is necessary to execute some code in order to reproduce the bug, paste it here below:
No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@rajevar I can't reproduce it with the latest version, are you sure you're using the latest one?

**Comment by rajevar** [comment]
sorry, my bad. I wasn't using the latest.
