### ISSUE TITLE
BUG: Incorrect type definition for PanelManager.addPanel

### ISSUE THREAD

**Issue by duclet** [GrapesJS/grapesjs#5144]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

All

### Reproducible demo link

None

### Describe the bug

The definition of the function located here: https://github.com/GrapesJS/grapesjs/blob/v0.21.1/src/panels/index.ts#L82 requires the data given as the full panel instance itself or an array of properties. The documentation on the site (https://grapesjs.com/docs/getting-started.html#panels-buttons) says the parameters given can be only an object with the properties (essentially a partial of the attributes of a panel).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
> The documentation on the site says the parameters given can be only an object with the properties

Sorry, where exactly do you read that statement?
