### ISSUE TITLE
BUG: none of the official GrapesJS plugins works with the new index.d.ts

### ISSUE THREAD

**Issue by jchautreux** [GrapesJS/grapesjs#5148]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

all and none, the bug is during the build

### Reproducible demo link

unnecessary

### Describe the bug

**How to reproduce the bug?**
1. create a blank project
2. use NPM to install GrapesJS and a plugin (preset-webpage in this example but "works" for all official plugins)
3. load GrapesJS using `import GrapeJS from 'grapesjs'`
4. attempt to load `preset-webpage` using `import plugin from 'grapesjs-preset-webpage';`

**What is the expected behavior?**
the project build correctly and the plugin is available

**What is the current behavior?**
the project failed to build because the d.ts of GrapeJS has changed

**FYI**
I could have created this ticket in each official plugins but I think one ticket to remind to update all  is enough

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
I'm closing this as related to https://github.com/GrapesJS/grapesjs/issues/5149

**Comment by jchautreux** [comment]
That's not really the same problem, in the #5149, the bug is related on how to set plugin options during the tool initialization.
Here, the bug is related to the last update of the project that has defined a new index.d.ts that is not compatible with the way of the plugins used it previously

**Comment by artf** [comment]
In the previous release `index.d.ts` had the same signature for plugins so I'm not sure to what change you're referring to
https://github.com/GrapesJS/grapesjs/blob/095466c8cc8034e54888d67beef4cb9296c823e4/index.d.ts#L50-L53

Can you share the exact error during the build?

**Comment by jchautreux** [comment]
```
Error: node_modules/grapesjs-preset-webpage/dist/index.d.ts:36:42 - error TS2503: Cannot find namespace 'grapesjs'.

36  modalImportContent?: string | ((editor: grapesjs.Editor) => string);
                                            ~~~~~~~~


Error: node_modules/grapesjs-preset-webpage/dist/index.d.ts:59:23 - error TS2503: Cannot find namespace 'grapesjs'.

59 declare const plugin: grapesjs.Plugin<PluginOptions>;
```

**Comment by artf** [comment]
Yeah, that part is documented in the [release note](https://github.com/GrapesJS/grapesjs/releases/tag/v0.21.1)

**Comment by jchautreux** [comment]
But the official plugins still use the old notation, so there are unusable for the moment unless i missed something

**Comment by artf** [comment]
Unfortunately I didn't find time to update plugins, but any help would be appreciated.

**Comment by Idaryss** [comment]
I do have the same issue with mjml plugin on my angular application. 
<img width="755" alt="Capture d’écran 2024-08-27 à 14 24 14" src="https://github.com/user-attachments/assets/d730d074-9571-4b38-a7b1-ff6c8372fc3e">

**Comment by Idaryss** [comment]
@artf  Hello, I am getting an error while implementing this solution. 
Before I used to declare a file name grapesjs.d.ts and have to write in it 'declare module grapesjs'

But looks like i need to remove it to use usePlugin helper. but once I remove this file I am getting the below issue: 

![Capture d’écran 2024-08-27 à 14 50 51](https://github.com/user-attachments/assets/d746a441-a899-42f4-a27f-504a9d742900)


Any support will be appreciated  OR can you please setup a quick simple Stackbliz using angular 17 or 18 and MJML plugin ? this would be awesome.
