### ISSUE TITLE
BUG: Non-named plugins and options

### ISSUE THREAD

**Issue by jchautreux** [GrapesJS/grapesjs#5149]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

all and none, the bug is during the build

### Reproducible demo link

unnecessary

### Describe the bug

**How to reproduce the bug?**
Use NPM to install GrapesJS to use it in a typescript project.
According to  the documentation, to set options of an non-named plugin, we have to defined this in `init`:
```
plugins: [myPlugin],
pluginsOpts: {
  [myPlugin]: {
     customField: 'customValue'
  }
}
```

**What is the expected behavior?**
The build of the project works

**What is the current behavior?**
The build failed with this error: `A computed property name must be of type 'string', 'number', 'symbol', or 'any'.`

**FYI**
We can use a named plugin but this way  of doing is mark as 'Deprecated' in favor of the non-named version
and can't be used for official plugins which are provided as non-named

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This seems to be related to https://github.com/microsoft/TypeScript/issues/35945
As a workaround you could do something like this for now:
```js
pluginsOpts: {
  [myPlugin.toString()]: {
     customField: 'customValue'
  }
}
```
I guess for the TS type safety we would need to introduce some kind of helper for plugins
```js
import grapesjs, { usePlugin } from 'grapesjs';
import somePlugin from 'gjs-plugin';

grapesjs.init({
  // ...
  plugins: [
    // no need for `pluginsOpts`
    usePlugin(somePlugin, { option1: 'A', option2: 'B', ... })
  ]
});
```

**Comment by jchautreux** [comment]
that sounds to be a good idea

**Comment by artf** [comment]
Added the helper [here](https://github.com/GrapesJS/grapesjs/commit/7d5d074e4d2735245541bfcbaad666e7bc37ea56) (I'll also update the docs with the usage later)
