### ISSUE TITLE
BUG: By default components are created using table in my demo project but the demo uses flex property to create components

### ISSUE THREAD

**Issue by shomeel** [GrapesJS/grapesjs#5164]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 112.0.5615.49 (Official Build) (x86_64)

### Reproducible demo link

https://jsfiddle.net/shomeelconovo/k7L2rthg/1/

### Describe the bug

I need help with something regarding the grapes.js. I have created a project and whenever I put a component in Canvas, every component has display : table property by default. However I have tried in grapes.js official demo, and every element has display : flex by default in their demo. What could be the issue and why the local project has different properties by default?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
https://github.com/GrapesJS/grapesjs/discussions/5163#discussioncomment-6162516
