### ISSUE TITLE
BUG: usePlugin is not a function

### ISSUE THREAD

**Issue by KevenDvorianoff** [GrapesJS/grapesjs#5167]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

All

### Reproducible demo link

None

### Describe the bug

Following the documentation on creating a plugin with the usage of typescript and using the "usePlugin" function to import the plugin into the editor, the browser displays the following error :

```
TypeError: g.usePlugin is not a function
```
It seems that the function declaration is not in the minified js of the node module dist.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sneddobuilds** [comment]
Getting the same issue.
