### ISSUE TITLE
BUG: Move method is not working as expected

### ISSUE THREAD

**Issue by krishnaeverestengineering** [GrapesJS/grapesjs#5175]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://codesandbox.io/s/adoring-margulis-873kdv

#### Context

Move component method doesn't work as expected.

```
if (component) {
      const { at } = opts;
      const index = this.index();
      const sameParent = component === this.parent();
      const sameIndex = index === at || index === at! - 1;

      if (!sameParent || !sameIndex) {
        if (sameParent && at && at > index) {
          opts.at = at - 1;
        }
        this.remove({ temporary: 1 });
        component.append(this, opts);
        this.emitUpdate();
      }
    }
    return this;
```

This piece of code doesn't work as expected.
```

if (component) {
      const { at } = opts;
      const index = this.index();
      const sameParent = component === this.parent();
      const sameIndex = index === at;

      if (!sameParent || !sameIndex) {
        this.remove({ temporary: 1 });
        component.append(this, opts);
        this.emitUpdate();
      }
    }
    return this;
```

this piece of code should work. When sameParent is false and target index is 1, then it won't move to 0 to 1 position for example

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krishnaeverestengineering** [comment]
Hi @artf. I have fixed this issue. Could you please provide access to the repo. I can raise a PR. Thanks

**Comment by krishnaeverestengineering** [comment]
https://github.com/GrapesJS/grapesjs/pull/5176

**Comment by artf** [comment]
Thanks @krishnaeverestengineering but this is actually the expected behaviour for moving the component inside the same parent. This is because the `at` should account also for the index of the component itself.

```
- index: 0
{ Component 1 }
- index: 1
{ Component 2 }
- index: 2
```
So, if you try to move "Component 1" at index 0 or 1, nothing will happen. If you need to move it below "Component 2" you have to indicate index 2

**Comment by krishnaeverestengineering** [comment]
> Thanks @krishnaeverestengineering but this is actually the expected behaviour for moving the component inside the same parent. This is because the `at` should account also for the index of the component itself.
> 
> ```
> - index: 0
> { Component 1 }
> - index: 1
> { Component 2 }
> - index: 2
> ```
> 
> So, if you try to move "Component 1" at index 0 or 1, nothing will happen. If you need to move it below "Component 2" you have to indicate index 2

But I don't understand the use case there. Usually `at ` should account for index in the last versions. How to move a component from 0  to index 1 then?

**Comment by artf** [comment]
> But I don't understand the use case there. Usually at  should account for index in the last versions. How to move a component from 0 to index 1 then?

As explained above, `at` behaves a bit unintuitivly if you move the component inside the same parent, so moving "Component 1" from 0 to 1 has no effect, you have to use `at: 2` to move it below "Component 2"

**Comment by krishnaeverestengineering** [comment]
Hi @artf , but the move function seems like working weirdly. When I tried to move component up and down using .move function, I didn't get the behaviour exactly. Can you please provide a logic to move component up and down?
