### ISSUE TITLE
BUG: bug

### ISSUE THREAD

**Issue by Zafermushtaha97** [GrapesJS/grapesjs#5211]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

v9.2

### Reproducible demo link

https://jsfiddle.net/szLp8h4n

### Describe the bug

I am using it in  vue3 project 
when I want to add new components , page is hanged and not response 
this  is my code :
```
  const selectedComponent = this.editoren.getSelected();
      if (selectedComponent) {
        const newComponent = this.editoren.DomComponents.getWrapper().append({
          type: 'text',
          content: 'New text component',
        });
        selectedComponent.components().add(newComponent);
        this.editoren.refresh();
          }
```
          

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gxanshu** [comment]
Hi there! 😊

I don't believe this is a bug with GrapesJS. I checked your reproduction link and tried adding a component to the canvas, and it worked perfectly fine for me without any issues. 👍

**Comment by artf** [comment]
You have to bypass Vue's Proxy observers https://github.com/GrapesJS/grapesjs/issues/4497#issuecomment-1213078160
