### ISSUE TITLE
BUG: Desktop Version on incorrectly mobile device

### ISSUE THREAD

**Issue by Staubgeborener** [GrapesJS/grapesjs#5221]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Safari 16.5

### Reproducible demo link

https://grapesjs.com/demo.html
https://staubgeborener.de/

### Describe the bug

I was trying out the official [demo](https://grapesjs.com/demo.html). I changed nothing, but simply click the `view code` button and download the html and css file as zip archive. These files were uploaded to my web server which is working perfectly on desktop devices. But as soon i visit this web server with a mobile device (for example iOS - safari browser) the website is still in desktop version and not in mobile version. The demo itself has a mobile version implemented.

**How to reproduce the bug?**
1. visit https://grapesjs.com/demo.html
2. click `view code` in upper right corner
3. click `Export to zip`
4. upload content to webserver

**What is the expected behavior?**
Getting the mobile version on mobile devices

**What is the current behavior?**
Getting the desktop version on mobile devices

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

Screenshots:

Opening website on mobile device (which is wrong)
![29F04642-DE16-4CFA-BDFF-C1AC5CF32983](https://github.com/GrapesJS/grapesjs/assets/28908603/c90a308b-ad6a-45a4-8403-b4ed3ca996a1)

Opening the website on desktop device (correct behaviour)
![grafik](https://github.com/GrapesJS/grapesjs/assets/28908603/5e8ef09e-c562-4032-ac47-e154b4e30516)

This is what i expected:
![grafik](https://github.com/GrapesJS/grapesjs/assets/28908603/2c6b1649-2b23-4146-a18c-97ade3c7fe32)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is not related to the core but simply a missing meta tag in the exported HTML from the demo.html
```html
<meta name="viewport" content="width=device-width,initial-scale=1">
```
If you want to submit a PR I'll be happy to merge it there
