### ISSUE TITLE
BUG: Contents of component with editable:false are still editable

### ISSUE THREAD

**Issue by riteshdalal** [GrapesJS/grapesjs#5245]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 114.0.5735.198

### Reproducible demo link

https://jsfiddle.net/riteshdalal/obnx7sg3/22/

### Describe the bug

**How to reproduce the bug?**
1. Create a component with editable:false in the model
2. Drop the component on the canvas

**What is the expected behavior?**
Contents of the non editable component should not be parsed by GJS 

**What is the current behavior?**
Contents of the non editable component are parsed and editable

Check the attached demo link

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riteshdalal** [comment]
@artf how do we create a component  such that gjs does not parse the children.

**Comment by riteshdalal** [comment]
> The `editable` property has no meaning by default and it's only used internally by other extended components like `Text` or `Image`

This used to work on older versions of GJS. Just stopped working in 0.21.3

**Comment by artf** [comment]
> This used to work on older versions of GJS. Just stopped working in 0.21.3

Honestly, I don't recall when `editable` ever worked in that way, but I might be wrong, if you want to share a live example with a specific version I'll take a look.

If you want the editor to completely skip the inner content, the only way would be to pass it as `content` and let `components` be empty in you `isComponent` method
```js
isComponent: el => {
  if (el.tagName === tagName && el.className.includes(newType)) {
    return {
      type: newType,
      content: el.innerHTML,
      components: [],
    }
  }
}
```
