### ISSUE TITLE
BUG:  editor?.Css.addRules(targetCss);

### ISSUE THREAD

**Issue by pittleCheung** [GrapesJS/grapesjs#5249]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

latest version of Chrome

### Reproducible demo link

null

### Describe the bug

**How to reproduce the bug?**

editor?.Css.addRules(targetCss);

**What is the expected behavior?**

editor?.Css.addRules(targetCss);  it  add style at end
<img width="826" alt="image" src="https://github.com/GrapesJS/grapesjs/assets/114127651/28425b0a-b9f7-46a8-b8bc-736aa112cc3c">

**What is the current behavior?**

I help  editor?.Css.addRules(targetCss,{at : 0});

I want to add a style to the beginning of an array instead of the end.
...

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is not a bug, `Css.addRules` doesn't have any option argument.
You can open a discussion in regard to this topic and we can see if it makes sense to introduce it

**Comment by pittleCheung** [comment]
ok, I  get it,I need to add some styles in front of an array, not at the end. such as arr.unshift(css) How can I do that? I might need a little help from you
