### ISSUE TITLE
BUG: Deleting a component without deleting its corresponding style, will adding new components later cause style conflicts?

### ISSUE THREAD

**Issue by pittleCheung** [GrapesJS/grapesjs#5263]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

latest version of Chrome

### Reproducible demo link

null

### Describe the bug

**How to reproduce the bug?**
<img width="1666" alt="image" src="https://github.com/GrapesJS/grapesjs/assets/114127651/c37e339a-e14f-486b-85fb-34c170b855dd">

**What is the expected behavior?**

**What is the current behavior?**
I use rewrite ctrl + c  and ctrl + v   logic
<img width="681" alt="image" src="https://github.com/GrapesJS/grapesjs/assets/114127651/c056010a-d680-439b-a381-0aa36fd7e2ac">

I have set up three parent components and use ctrl+c,ctrl+v  to added some child components to them. After deleting these child components, their styles still remain.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
I don't see how this is a core bug. 
You're using your own copy/paste logic and it doesn't even seem correct, you should take care of the unique ids of each component/rule.

> After deleting these child components, their styles still remain.

If you're copying all matched styles it would also contain styles used by other elements so you can't simply expect those styles to be deleted.

Please, if you're submitting a bug, ALWAYS provide a reproducible demo.

**Comment by pittleCheung** [comment]
Yes , you are right, I copying all matched styles ,so I can paste anywhere , even cross-browser paste, I find this to be extremely useful. When I delete a component, it does not remove the corresponding styles. This is a major issue， And when I copy and paste multiple times on the same website, it leads to a lot of redundant styles and easily causes style conflicts.  so I can't simply expect those styles to be deleted. If possible, I would appreciate some suggestions.

`If you're copying all matched styles it would also contain styles used by other elements so you can't simply expect those styles to be deleted.`
