### ISSUE TITLE
BUG: autoplay for youtube or vimeo doesn't work

### ISSUE THREAD

**Issue by SLain123** [GrapesJS/grapesjs#5268]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v115

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Drag and drop video component to canvas.
2. Select youtube or vimeo and add video id.
3. Activate autoplay checkbox.
4. Publish or preview the page.

**What is the expected behavior?**
Video must autoplay after user open page.

**What is the current behavior?**
Video doesn't launch.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SLain123** [comment]
I can fix the bug myself, but I can't push my branch with fix to repo. It seems like I don't have permission for pushing or create new branch.

**Comment by artf** [comment]
@SLain123 you have to create a PR from your fork https://stackoverflow.com/questions/38918942/pull-request-from-a-different-repository
