### ISSUE TITLE
Border of images and some elements in the wrong position

### ISSUE THREAD

**Issue by saharelhage** [GrapesJS/grapesjs#5286]
On smaller laptop screens (macbooks for example), the border of images and some elements are in the wrong position (when i click to move or resize an image)
I am not having this issue when the editor gets rendered on bigger screens.

I am not sure if there is a config step that i'm missing.

Can anyone please assist? Is this a common issue?

For example:
<img width="217" alt="Screenshot 2023-08-08 at 3 20 19 PM" src="https://github.com/GrapesJS/grapesjs/assets/121887023/9b83c4a2-c944-4faf-94e0-3d6bca9c80d1">
<img width="245" alt="Screenshot 2023-08-08 at 3 20 25 PM" src="https://github.com/GrapesJS/grapesjs/assets/121887023/8526ca87-e312-4fdb-ae1e-92799398805d">

_Originally posted by @saharelhage in https://github.com/GrapesJS/grapesjs/discussions/5285_

**Comment by artf** [comment]
@saharelhage please avoid converting discussions to issues. The GitHub Issues should only be created from [here](https://github.com/GrapesJS/grapesjs/issues/new/choose) by properly following the template.
