### ISSUE TITLE
BUG: Can't overwrite gjs-selected class

### ISSUE THREAD

**Issue by craigharman** [GrapesJS/grapesjs#5293]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Arc 1.1.1

### Reproducible demo link

https://jsfiddle.net/3bprucnv/3/

### Describe the bug

**How to reproduce the bug?**

Add custom css rule for .gjs-selected eg. change the border color to red.

.gjs-selected {
  outline-color: red;
}

**What is the expected behavior?**
When selecting an element within grapesjs editor, the border of the selection should be red.

**What is the current behavior?**
Border/outline remains blue.

Note: All other css overrides related to selection/highlighting are successfully overwritten (eg. highlighter, highlighter-sel)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Please refer to https://github.com/GrapesJS/grapesjs/issues/3515
