### ISSUE TITLE
BUG: "component:add" event triggers when components are moved

### ISSUE THREAD

**Issue by rajevar** [GrapesJS/grapesjs#5305]
### GrapesJS version
0.21.4
- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Version 113.0.5672.63 

### Reproducible demo link

https://jsfiddle.net/szLp8h4n/11/

### Describe the bug

**How to reproduce the bug?**
Move any of the text components around in the page.
An alert will be displayed.

could be a regression.
https://github.com/GrapesJS/grapesjs/issues/868
Don't see an option to reopen the bug, so creating new one.

**What is the expected behavior?**
Alert will be displayed only on adding a new components to the canvas

**What is the current behavior?**

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Hi @rajevar I think you're looking for `component:create` event, as `component:add` works as expected (eg. might be used to track any new movement inside a specific component)
