### ISSUE TITLE
BUG: Editor not subscribing to selector:remove 

### ISSUE THREAD

**Issue by BenKhz** [GrapesJS/grapesjs#5316]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v115.0.5790.170 

### Reproducible demo link

https://jsfiddle.net/BenKhz/yfwqc6mu/1/

Referencing [The docs here](https://grapesjs.com/docs/api/selector_manager.html#available-events)

### Describe the bug

1. Open Provided fiddle [Here](https://jsfiddle.net/BenKhz/yfwqc6mu/1/)
2. Select a component on canvas and add a class via the selector manager. (`add` and `update` events will be caught)
3. Remove a class from the class manager
4. Event Listener for `editor.on('selector', () =>{})` doesn't execute.

**What is the expected behavior?**
Expect removal of class to trigger `selector:remove` event

**What is the current behavior?**

 Editor.on doesn't see any remove events for the selector manager. Referencing the docs, the catch all event "selector" sees `add` and `update` but never a `remove` event.

I may be misunderstanding the purpose of these events; if so, can you provide clarification or perhaps a workaround? Trying to trigger custom behavior on all components when a specific class is removed.

Thank you for all your work. truly a great project! 🚀

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Hi @BenKhz that's happening because `selector*` events are related to the global Selectors container (when you remove a selector from the component, the Selector itself is still there as it could be used in other places), if you want to track change to the selectors on components, you have to use `component:update:classes` event
