### ISSUE TITLE
BUG: Undo doesn't refresh class on component

### ISSUE THREAD

**Issue by AFriboulet-ii** [GrapesJS/grapesjs#5319]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome V116.0.5845.96

### Reproducible demo link

https://jsfiddle.net/Adrien_Friboulet/npdkshaf/8/

### Describe the bug

https://github.com/GrapesJS/grapesjs/assets/128728949/e85b65c4-53ad-43d0-9f5f-74dc0a181dd0

**How to reproduce the bug?**
1. Open Provided fiddle [Here](https://jsfiddle.net/Adrien_Friboulet/npdkshaf/8/)
2. Drop a component "paragraph"
3. Select component previously drop and click on the gear in the toolbar
4. Click on undo button in the top

**What is the expected behavior?**
Expect to click on the undo button, the previous class set of component are correctly rendered on canvas

**What is the current behavior?**
On click on the undo button, the previous class set of a component is not correctly rendering on canvas but change in the selector manager

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @AFriboulet-ii I will fix it for the next release.
