### ISSUE TITLE
BUG: Upload Image or Asset is not triggering on File/Image selection

### ISSUE THREAD

**Issue by SwapnilSoni1999** [GrapesJS/grapesjs#5320]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v114

### Reproducible demo link

none

### Describe the bug

**How to reproduce the bug?**
1. I'm using [grapesjs-react](https://www.npmjs.com/package/grapesjs-react) and using `assetManager`
2. My config looks like this
```js
{
                    upload: `${globals.settings.cmsUrl}/upload-image`,
                    uploadName: "image",
                    headers: {
                        Authorization: `Bearer ${token}`,
                    },
                    autoAdd: true,
                    multiUpload: false,
}
```
PS: I do have a working endpoint which I've tested already.

3. Now goto the editor in browser
4. add image
5. select image from the system
6. then no upload request is made

**What is the expected behavior?**
Expected is it should trigger a request and upload the asset to given url

**What is the current behavior?**
its not uploading anywhere instead its putting base64 image in DOM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamuddeshya** [comment]
Facing same issue

**Comment by deepanshu-ht** [comment]
+ 1

**Comment by artf** [comment]
Just tried the same configuration and all works as expected.

Might be related to your grapesjs version or the `grapesjs-react` itself.

Please avoid creating BUG issues if you're not able to provide a reproducible demo with the latest version of GrapesJS.

I'd also highly recommend switching to the [official GrapesJS React wrapper ](https://github.com/GrapesJS/react) which also allows you to implement a completely declarative custom UI for your editor.
