### ISSUE TITLE
BUG: editable text after remove focus of RTE, returns back previous state of content. 

### ISSUE THREAD

**Issue by sdimitrenco** [GrapesJS/grapesjs#5328]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

https://jsfiddle.net/sdimitrenco/wao1rh0q/30/

### Describe the bug

That is my components struct

```
  {
    "type": "link",
    "components": [
      {
        "type": "image",
        "attributes": {
          "src": "http://localhost:8003/swt/upload/files/svg_images/envelope-square-solid.svg",
        }
      },
      {
        "tagName": "span",
        "type": "text",
        "content": "some@test.com",
      }
    ]
  }
```

If I change the text in the span tag in the text editor, then remove focus from that word, it returns the previous state of the text. The structure of the components looks normal, a link, but inside the picture and text inside the span tag.

DEMO
![image](https://github.com/GrapesJS/grapesjs/assets/39157717/1a21766a-d945-4d0b-9360-13390722c5dd)

LIVE
https://jsfiddle.net/sdimitrenco/wao1rh0q/30/
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You shouldn't have `"content"` inside your text span, indeed if you replace it with `"components": "some@test.com",` it will work properly.
