### ISSUE TITLE
BUG:  Deleting a component without deleting its corresponding style

### ISSUE THREAD

**Issue by pittleCheung** [GrapesJS/grapesjs#5346]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

latest version of Chrome

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
<img width="1665" alt="image" src="https://github.com/GrapesJS/grapesjs/assets/114127651/657cbaf6-7e87-4702-ac7f-36c710464728">

**What is the expected behavior?**
it's style maybe reduce,

**What is the current behavior?**
First of all, my editor only uses one page. Every time I switch pages, it will replace the current configuration with a page from the backend. Therefore, when I implement the public header and tail, I can use editor.CodeManager.getCode(component , 'html', {cssc: editor.CssComposer}); to replace the component, but I cannot use editor.CodeManager.getCode(component, 'css', {cssc: editor.CssComposer}) to replace the style, which will cause if If I operate (delete and add components) the components inside the head and tail multiple times, a lot of redundant styles will appear.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
https://github.com/GrapesJS/grapesjs/issues/5263

I copying all matched styles ,so I can paste anywhere , even cross-browser paste, I find this to be extremely useful. When I delete a component, it does not remove the corresponding styles. This is a major issue， And when I copy and paste multiple times on the same website, it leads to a lot of redundant styles and easily causes style conflicts. so I can't simply expect those styles to be deleted. If possible, I would appreciate some suggestions.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pittleCheung** [comment]
Extended (https://github.com/japo32)](https://github.com/GrapesJS/grapesjs/issues/1855)'s idea,

**Comment by pittleCheung** [comment]
Extended [](https://github.com/GrapesJS/grapesjs/issues/1855) idea,

**Comment by pittleCheung** [comment]
Extended   idea  from https://github.com/GrapesJS/grapesjs/issues/1855

**Comment by artf** [comment]
Here it's explained how to create components with related styles
https://grapesjs.com/docs/modules/Components.html#components-css

Only in that case, it would be safe for the editor to delete related styles.
