### ISSUE TITLE
BUG: canvas.script entries can not be JS modules

### ISSUE THREAD

**Issue by rozek** [GrapesJS/grapesjs#5353]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 1.56.20 Chromium: 115.0.5790.171 (Offizieller Build) (arm64)

### Reproducible demo link

none

### Describe the bug

links entered into

```
    let Editor = grapesjs.init({
      canvas: {
        scripts:[...],
        ...
```

can not refer to JavaScript modules, or you may run into the following error:

```
Uncaught SyntaxError: Cannot use import statement outside a module
```

This makes it **really** difficult to use modern JavaScript in combination with GrapesJS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
```js
scripts: [
  { src: '...file.js', type: 'module' },
],
```

**Comment by rozek** [comment]
good to know, thanks
