### ISSUE TITLE
BUG: Uncaught TypeError: Cannot read properties of undefined (reading 'Canvas') while dragging a component in Layer Manager Panel

### ISSUE THREAD

**Issue by Sw33tgt** [GrapesJS/grapesjs#5378]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v116.0.5845.97

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Select any component from the canvas
2. Open the Layer Manager Panel
3. Select the first "Section" component
4. Use the arrow to move the section and change the order

**What is the expected behavior?**
The section should move the the new position

**What is the current behavior?**
The console is throwing an error Uncaught TypeError: Cannot read properties of undefined (reading 'Canvas') and Uncaught TypeError: Cannot read properties of undefined (reading 'method')

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```
![image](https://github.com/GrapesJS/grapesjs/assets/144697108/1ec72b5f-c98a-4991-a140-b2fa65782a36)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sw33tgt** [comment]
I downgraded to v0.21.4 and I don't have the issue anymore, so this is only occurring on the latest version available.

**Comment by padcom** [comment]
Having the same issue in the simplest examples. Downgrading do .4 makes it go away. Regression?

**Comment by artf** [comment]
Yeah fixed already [here](https://github.com/GrapesJS/grapesjs/issues/5355). I'll push a new release for the end of this week.
