### ISSUE TITLE
BUG: main.scss is missing in 0.21.6

### ISSUE THREAD

**Issue by quentin-bettoum** [GrapesJS/grapesjs#5408]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox 118

### Reproducible demo link

none

### Describe the bug

Hello there,

I have themed GrapesJS following the instructions of the doc here: https://grapesjs.com/docs/getting-started.html#theming
But with 0.21.6, it's not possible anymore to `@import "grapesjs/src/styles/scss/main.scss";` in SCSS, because the file is missing in the `node_modules/grapejs/` folder

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joukhar** [comment]
yeah `src` folder is missing

**Comment by artf** [comment]
Same issue as https://github.com/GrapesJS/grapesjs/issues/5392
