### ISSUE TITLE
BUG: After applying the text color not able to set the background color

### ISSUE THREAD

**Issue by kishanp102** [GrapesJS/grapesjs#5442]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome

### Reproducible demo link

https://jsfiddle.net/a3xgLm7c/3/

### Describe the bug

**How to reproduce the bug?**
1. Select the text and apply the text color
2. Select the same text and apply the background color

**What is the expected behavior?**
1. Both color should apply 

**What is the current behavior?**
1. Background color should apply after applying the text color

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mapsmarketing** [comment]
Hi @kishanp102 ,

I tried to reproduce the issue with the steps described but both the text and background colours are being applied (please see screenshot).

<img width="318" alt="image" src="https://github.com/GrapesJS/grapesjs/assets/79551469/74b22828-610a-4530-9582-96c0c120a805">

**Comment by kishanp102** [comment]
Drag and drop the text component then apply the font color and click outside again click on the text and put the background color it is not applying
[screencast-jsfiddle.net-2023.10.11-09_19_42.webm](https://github.com/GrapesJS/grapesjs/assets/43177161/1f7e270d-a144-41fa-84c1-763c7896ae18)

**Comment by mapsmarketing** [comment]
Yep, you are right @kishanp102 it doesn't apply a new background colour on it after you've already set one. It's definitely a bug.

**Comment by kishanp102** [comment]
@artf can you look into this issue
