### ISSUE TITLE
BUG: Loading `component` and `styles` from `pageManager`

### ISSUE THREAD

**Issue by mapsmarketing** [GrapesJS/grapesjs#5460]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v117.0.5938.149

### Reproducible demo link

https://jsfiddle.net/9oLrsvya/

### Describe the bug

**How to reproduce the bug?**
1. Please see the `pageManager` object in the jsfiddle

**What is the expected behavior?**
Looking at the following documentation: https://grapesjs.com/docs/api/pages.html#pages

It should load in the `component` and `styles` from the `pageManager` correctly into the editor. 

**What is the current behavior?**
When you check the code via "view code" in the editor you'll notice neither the exact HTML neither the styles have correctly loaded. The `body` tag does not retain the `ID` tag that the editor adds when applying any kind of styling to it which means the styling won't work. And the CSS hasn't loaded in correctly at all.

---

If it is a confirmed bug, I'd be happy to attempt to fix it. It would be great to roughly know where the `component` and `styles` are being loaded from as I am not intimately familiar with the project files.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Hi @mapsmarketing currently GrapesJS is not able to properly import HTML documents as string, so the parser skips elements like `html`, `head`, `body` and returns only what is parsed inside the `body`, one workaround you could do right now is to pass component as object
```js
component: {
  attributes: { id: 'ignt' },
  components: '<div class="my-el">Testing world!</div>',
},
```
Regarding the styles, it's the browser's default CSSOM parser issue, please refer to this [plugin](https://github.com/GrapesJS/parser-postcss)

**Comment by mapsmarketing** [comment]
Hi @artf ,

I've found a way to get the `body` attributes along with the styles saving correctly via the following method:
```
const pageManager = editor.Pages;
const page = pageManager.get('my-page-id').toJSON();
const component = pageManager.get('my-page-id').getMainComponent();
page.styles = editor.getCss({ component });
```

I noticed that your [Page.toJSON](https://github.com/GrapesJS/grapesjs/blob/e03dfc7483b7fd936f3580bee78fee6d03c2b055/src/pages/model/Page.ts#L134-L149) outputs everything of the specified page. However, it doesn't seem to output the `styles` correctly (it's always set as undefined for me), so I retrieve the styles for the active page via the editor and override the ones in the JSON. I believe `styles` are not set due to the `if (!props.frames)` check you have in [Page.ts](https://github.com/GrapesJS/grapesjs/blob/e03dfc7483b7fd936f3580bee78fee6d03c2b055/src/pages/model/Page.ts#L55-L58)

The below is an example of how I'm loading in the HTML. I am using `frames` since `component` doesn't work with the supplied structure. I am loading in the styles without the use of the parser plugin and it seems to be loading in without issues.
```
const pageJSON = {...}; // Contains the `frames` and `styles`
const editor = grapesjs.init({
    pageManager: {
        pages: [
            {
                id: 'my-page-id',
                frames: pageJSON.frames,
                styles: pageJSON.styles,
            }
        ]
    }
});
```

I also noticed that the [PageManager.select](https://github.com/GrapesJS/grapesjs/blob/e03dfc7483b7fd936f3580bee78fee6d03c2b055/src/pages/index.ts#L254-L261) function doesn't update styles when switching between the pages which forces me to run: `editor.setStyle(pageJSON.styles);`

**Comment by mapsmarketing** [comment]
One annoying thing is that the editor is prepending the below default styles which when saving the styles has numerous duplicates of it:
```
* {
  box-sizing: border-box;
}
body {
  margin: 0;
}
```

**Comment by artf** [comment]
I'd suggest you following [this](https://grapesjs.com/docs/modules/Storage.html#skip-initial-load) to properly load your JSON projects. 
Styles are stored in a separate module, that's the reason why you don't see them per pages.

**Comment by mapsmarketing** [comment]
Hi @artf ,

I saw that in your docs. I am storing the pages separately in my database at the moment which is why I was approaching it in the way I have. 

I might abandon this and try and make it work with your  Storage Manager instead in some way.

Have an awesome weekend Artf
