### ISSUE TITLE
BUG: multiple pages in importing css is not accessing

### ISSUE THREAD

**Issue by MaulikAarrsol** [GrapesJS/grapesjs#5464]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome 117.0.5938.152

### Reproducible demo link

no

### Describe the bug

**How to reproduce the bug?**
1. ... grapesjs pages multiple page in importing css not access
2. ... importing css is not working

**What is the expected behavior?**
...

**What is the current behavior?**
...

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Please follow the bug issue template properly

> If you don't indicate a reproducible demo with relative steps to reproduce the bug, the issue might be CLOSED.
