### ISSUE TITLE
BUG: clone tabs and clone tab is not right now 

### ISSUE THREAD

**Issue by pittleCheung** [GrapesJS/grapesjs#5484]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

latest version of Chrome

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

https://github.com/GrapesJS/components-tabs
question one 

<img width="1421" alt="image" src="https://github.com/GrapesJS/grapesjs/assets/114127651/a3afe6c7-d644-40f0-97e5-cc3e3c595939">

click the tab clone , the tab four is be cloned , look the below img

<img width="1425" alt="image" src="https://github.com/GrapesJS/grapesjs/assets/114127651/90db58ba-ba7a-404a-8061-a7f232d5e400">

question two
<img width="1434" alt="image" src="https://github.com/GrapesJS/grapesjs/assets/114127651/0cfd4d79-0866-4ad3-88ff-eb41b0b85576">

click the tabs clone, The picture after cloning is as follows
<img width="1424" alt="image" src="https://github.com/GrapesJS/grapesjs/assets/114127651/a0f2f3e7-6e0a-403b-b09a-209447b0821c">

 The contents of the tab are not clone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Please, open bug issues only if related to the core library, not plugins.
