### ISSUE TITLE
BUG: Style Manager doesn't display multiple rules for the same class

### ISSUE THREAD

**Issue by MaxDBenson** [GrapesJS/grapesjs#5487]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox

### Reproducible demo link

https://jsfiddle.net/497zkrpm/1/

### Describe the bug

**How to reproduce the bug?**
1. Select the "Hello World" component
2. Open the Style Manager and make sure "myclass" is checked in the classes section
3. Check the values for the "height" and "background-color" properties

**What is the expected behavior?**
The Style Manager should reflect all rules associated with the selected class (in this case `.myclass {height: 100px}` and `.myclass {background-color: green}`

**What is the current behavior?**
The Style Manager only reflects the first rule associated with the selected class (in this case: `.myclass {height: 100px}`

https://github.com/GrapesJS/grapesjs/assets/14164766/1a8dccad-1314-4291-8644-b8438cc0126e

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Not a bug, the style manager handles only one rule at a time, if you want more advanced usage, you can use the API and implement your functionalities (eg. selecting different rules with the same selector)

**Comment by MaxDBenson** [comment]
> Not a bug, the style manager handles only one rule at a time, if you want more advanced usage, you can use the API and implement your functionalities (eg. selecting different rules with the same selector)

I see.  Would you mind elaborating a little on how to go about that? 

Also, it doesn't seem like the style manager does handle only one rule at a time; since when I select a class I see property/value settings that were applied to the ID, and vice-versa.
