### ISSUE TITLE
BUG: replaceWith method doesn't have string type

### ISSUE THREAD

**Issue by MaxwellTheSecond** [GrapesJS/grapesjs#5503]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

none

### Describe the bug

replaceWith method from Component.ts doesn't have a type for string.

**What is the expected behavior?**
I should be able to replace a component with a string like in the example `component.replaceWith('<div>Some new content</div>');`

**What is the current behavior?**
![grapesproblem](https://github.com/GrapesJS/grapesjs/assets/81811949/67837b49-a81f-4c07-a8b1-9d5481f457a1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MaxwellTheSecond** [comment]
PR: #5504

**Comment by artf** [comment]
Merged https://github.com/GrapesJS/grapesjs/pull/5504
