### ISSUE TITLE
BUG: Error autoplay youtube

### ISSUE THREAD

**Issue by brenoassp** [GrapesJS/grapesjs#5542]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 119.0.6045.200 64 bits

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Drag and drop a video block into the canvas
2. Click on the video and select YouTube as the Provider.
3. Add any video ID, for instance, lDK9QqIzhwk, and check the Autoplay option.
4. Click on the view code button and look for the iframe generated. The URL is something like: `https://www.youtube.com/embed/lDK9QqIzhwk?&autoplay=1&muted=1`.

**What is the expected behavior?**
The expected behavior is to autoplay the video with the generated HTML.

**What is the current behavior?**
The video is not being played automatically with the sound muted with the generated HTML.
I created an empty HTML and put this iframe tag in it and when I changed from `muted=1` to `mute=1` it worked. Maybe YouTube changed this query parameter recently? I don't know.

I would like to know if anyone knows something about it and if I should make a PR changing the query param from `muted` to `mute` to fix this.

Thank you

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Looks like the muted property was correct for Vimeo but not for Youtube. I'll push the fix, thanks.
