### ISSUE TITLE
BUG:   Too many classes will cause the webpage to crash

### ISSUE THREAD

**Issue by pittleCheung** [GrapesJS/grapesjs#5556]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

latest version of Chrome

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**

editor.addComponents(` <ul
              class="mb-5 flex list-none flex-row flex-wrap border-b-0 pl-0"
              role="tablist"
              data-te-nav-ref
            >
          <li role="presentation">
            <a
              class="my-2 block border-x-0 border-b-2 border-t-0 border-transparent px-7 pb-3.5 pt-4 text-xs font-medium uppercase leading-tight text-neutral-500 hover:isolate hover:border-transparent hover:bg-neutral-100 focus:isolate focus:border-transparent data-[te-nav-active]:border-primary data-[te-nav-active]:text-primary dark:text-neutral-400 dark:hover:bg-transparent dark:data-[te-nav-active]:border-primary-400 dark:data-[te-nav-active]:text-primary-400"
              data-te-toggle="pill"
              data-te-nav-active
              role="tab"
              aria-controls="tabs-home"
              aria-selected="true"
              data-gjs-type="text"
              >Home</a
            >
          </li>
          <li role="presentation">
            <a
              href="#tabs-profile"
              class="my-2 block border-x-0 border-b-2 border-t-0 border-transparent px-7 pb-3.5 pt-4 text-xs font-medium uppercase leading-tight text-neutral-500 hover:isolate hover:border-transparent hover:bg-neutral-100 focus:isolate focus:border-transparent data-[te-nav-active]:border-primary data-[te-nav-active]:text-primary dark:text-neutral-400 dark:hover:bg-transparent dark:data-[te-nav-active]:border-primary-400 dark:data-[te-nav-active]:text-primary-400"
              data-te-toggle="pill"
              data-te-target="#tabs-profile"
              role="tab"
              aria-controls="tabs-profile"
              aria-selected="false"
              data-gjs-type="text"
              >Profile</a
            >
          </li>
          
        </ul>
         <div class="mb-6">
          <div
            class="hidden opacity-100 transition-opacity duration-150 ease-linear data-[te-tab-active]:block"
            id="tabs-home"
            role="tabpanel"
            aria-labelledby="tabs-home-tab"
            data-te-tab-active
          >
            Tab 1 content
          </div>
          <div
            class="hidden opacity-0 transition-opacity duration-150 ease-linear data-[te-tab-active]:block"
            id="tabs-profile"
            role="tabpanel"
            aria-labelledby="tabs-profile-tab"
          >
            Tab 2 content
          </div>
        </div>`)

**What is the expected behavior?**
...

**What is the current behavior?**

When I click on the a tag, the entire web page will be paralyzed.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Already reported and fixed https://github.com/GrapesJS/grapesjs/issues/5525
