### ISSUE TITLE
BUG: Import button is removing all styling from all pages.

### ISSUE THREAD

**Issue by prateekkumar-ec** [GrapesJS/grapesjs#5570]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Latest Version

### Reproducible demo link

N/A( I can share video if required for further conversation)

### Describe the bug

**How to reproduce the bug?**
1. Suppose you have some content on your current page with some styles over that.
2. Now create one new page in the same project.
3. Click on the import button on the editor's header leave the pop-up empty and hit the import button of pop-up window.
4. Now go and check the first page. It will lose all of its CSS.

**What is the expected behavior?**
The first page should remain unchanged if you are importing something on other page.

**What is the current behavior?**
The styles of one page is affected by importing nothing in the other page.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Afrin127329** [comment]
It would be great if you could kindly attach a video. Not sure about the empty pop-up thing
