### ISSUE TITLE
BUG: Layer manager not refreshing on page change

### ISSUE THREAD

**Issue by thigh** [GrapesJS/grapesjs#5593]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

MS Edge 120.0.2210.91

### Reproducible demo link

none available

### Describe the bug

**How to reproduce the bug?**
1. update to latest grapesjs version
2. set up a multi-page project
3. note the current layer manager hierarchy
4. invoke the pagemanager.select(pageId) method for a different page other than the currently selected page
5. the layer manager still reflects the hierarchy of the previous page even though the page manager shows the new page as currently active and the canvas correctly renders the newly selected page
6. Downgrade to grapesjs v0.21.6 and repeat steps 3-5. The layer manager will correctly reflect the hierarchy of the active page each time a different page is selected

**What is the expected behavior?**
...Tthe layer manager should updated to reflect the active page layer hierarchy

**What is the current behavior?**
... The layer manager does not change despite changing the active page via the page manager select() method. The canvas updates successfully but the layer manager still shows the first pages hierarchy without updating.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks for the report @thigh will fix it

**Comment by sunnynk19** [comment]
Hi @thigh, Looks like still not working. Have you deployed the latest npm package?

**Comment by artf** [comment]
Not yet published, you can find here all the releases https://github.com/GrapesJS/grapesjs/releases
