### ISSUE TITLE
BUG: Cannot expand previously empty layers

### ISSUE THREAD

**Issue by Ju99ernaut** [GrapesJS/grapesjs#5607]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v120.0.6099.199

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Drag the column 1 block onto the canvas
2. Drag any other block into the cell for example text
3. Select the cell
4. Open the layers panel

**What is the expected behavior?**
We should be able to expand the cell and select the element inside the cell via the layers

<img width="1438" alt="Screenshot 2024-01-10 at 5 42 36 PM" src="https://github.com/GrapesJS/grapesjs/assets/48953676/043150f3-9c71-4886-b923-7b8091b0968f">

**What is the current behavior?**
We cannot expand the cell to access any elements inside since the carret isn’t visible.

<img width="1436" alt="Screenshot 2024-01-10 at 5 39 51 PM 1" src="https://github.com/GrapesJS/grapesjs/assets/48953676/b86a865d-6da0-4818-b2bb-a1a8d983cbc9">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Good catch, I'll fix it
