### ISSUE TITLE
BUG: Old Component script is not deleted on Import. Resulting in duplicate scripts

### ISSUE THREAD

**Issue by Ashwinvalento** [GrapesJS/grapesjs#5618]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Edge v120.0.2210.121

### Reproducible demo link

https://codepen.io/ashwinvalento/pen/jOJMPqx

### Describe the bug

If we have set `config.parser.optionsHtml.allowScripts: true` and create a component with a script, Then when we import code using the `grapesjs-preset-webpage` plugin, the script tag is duplicated. 

**How to reproduce the bug?**

In the Demo link (https://codepen.io/ashwinvalento/pen/jOJMPqx)
1. Drop the "Duplicate Script Block" to the canvas. (This component has a script)
2. Click on the Import code option. Notice that there is only 1 script block of the "Duplicate Script Block"
3. Click import button.
4. Again click on the Import code option and notice that there are 2 blocks now.

**What is the expected behavior?**
When import is clicked, the script of the previously imported component should be removed automatically and new code should be imported

**What is the current behavior?**
Old script is not removed and new script is added which creates a duplicate. As a result, the component script exeutes multiple times

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Reimporting directly JS as a component was never possible, so it's treated as a new one.

**Comment by Ashwinvalento** [comment]
Is there any way we can identify scripts of existing components and delete them on import? we wont be able to remove all the script tags since we would need to retain the scripts added manually.
