### ISSUE TITLE
BUG: configuring an onStart() resize callback prevents resizing

### ISSUE THREAD

**Issue by kla-ko** [GrapesJS/grapesjs#5630]
### GrapesJS version

- [x] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Version 120.0.6099.225

### Reproducible demo link

https://jsfiddle.net/wattnu/y8L6whun/

### Describe the bug

**How to reproduce the bug?**
1. Goto jsfiddle
2. run the code
3. on the canvas, select the blue div component
4. try to drag the resizer handle located at bottom center
5. the resize handle doesn't move with your mouse
6. In the js code, check my plugin implementation on the top. There, consider the part:
  ```
   resizable: {
            tl: 0, tc: 0, tr: 0, cl: 0, cr: 0, bl: 0, bc: 1, br: 0, 
            onStart: (event, opt) => { console.log('resize started') } ,
          },
  ```
7. comment out the onStart config --> ``// onStart: (event, opt) => { console.log('resize started') } ,`` 
8. re-run the fiddle. Now it is possible to resize the blue block.

**What is the expected behavior?**
The component should be resizable even when configuring an ``onStart`` calback

**What is the current behavior?**
The component cannot be resized if an ``onStart`` callback is configured. The callback is executed though.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Good catch, will fix it
