### ISSUE TITLE
BUG: Undo manager add() not working as expected

### ISSUE THREAD

**Issue by Harshsne26** [GrapesJS/grapesjs#5631]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v91

### Reproducible demo link

--

### Describe the bug

**How to reproduce the bug?**
I wanted to add an change to the undomanager stack .
`var components = editor.Components;
editor.UndoManager.add(components.getComponents().models);`

**What is the expected behavior?**
The change added using um.add() should be added ..and when i press undo and redo this change should also be displayed.

**What is the current behavior?**
The change is not added.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@Harshsne26 you need to provide a reproducible demo for a bug
