### ISSUE TITLE
BUG: Add a change to the undomanager  

### ISSUE THREAD

**Issue by Harshsne26** [GrapesJS/grapesjs#5632]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v91

### Reproducible demo link

https://codepen.io/dhanadsp1120/pen/ExrRvOB

### Describe the bug

How to reproduce the bug?
1.Disable the undo manager by invoking um.stop().
2.Make alterations to the content.
3.Re-enable the undo manager using um.start().

**What is the expected behavior?**
When the undo manager resumes, any modifications made after its pause should be treated as a single change. This ensures that clicking "undo" will revert the entire set of alterations to the state prior to the undo manager's interruption.

**What is the current behavior?**
The changes made after undomanager stopped is not included as change after it is resumed.Upon selecting the undo option, the changes persist and are not rolled back as expected.

Also i have tried added the change to the undomanager :
`    var components = editor.Components;    
editor.UndoManager.add(components.getComponents().models);`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
> When the undo manager resumes, any modifications made after its pause should be treated as a single change. This ensures that clicking "undo" will revert the entire set of alterations to the state prior to the undo manager's interruption.

Sorry, but this is not how UndoManager start/stop works. When you disable it, all the changes are simply skipped from the UndoStack. 
What you're mentioning is a programmatic grouping of changes, for sure an interesting thing but at the moment is not supported so I'm not considering this a bug.
I'd suggest proposing this to the [Roadmap](https://github.com/GrapesJS/grapesjs/discussions/5291), if more people need this, we can think about implementing it.
