### ISSUE TITLE
BUG: sourcemap not loading for CompoentTextView

### ISSUE THREAD

**Issue by addlistener** [GrapesJS/grapesjs#5668]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 121.0.6167.139 (Official Build) (x86_64)

### Reproducible demo link

none.

### Describe the bug

**How to reproduce the bug?**
1. add customRte and set breakpoints
2. click step out until it reaches the logic in ComponentTextView

**What is the expected behavior?**
sourcemap loads

**What is the current behavior?**
sourcemap NOT loaded for ComponentTextView, but already loaded for RichTextEditorModule
<img width="557" alt="image" src="https://github.com/GrapesJS/grapesjs/assets/4531670/7b110b3d-4a19-4342-9b5d-4fb6cd950508">

<img width="558" alt="image" src="https://github.com/GrapesJS/grapesjs/assets/4531670/fa004188-34e5-414d-b253-ae937d7af63e">

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
<GjsEditor
          className="gjs-custom-editor"
          grapesjs="/grapesjs/dist/grapes.min.js"
          grapesjsCss="/grapesjs/dist/css/grapes.min.css"
/>
```
using local copy from "npm install grapesjs" because the remote source map does not work for me
version copied from the source file: /*! grapesjs - 0.21.7 */

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
I can only suggest to check properly the source map path 
<img width="346" alt="Screenshot 2024-02-12 at 08 45 32" src="https://github.com/GrapesJS/grapesjs/assets/11614725/ee135460-a758-4aef-96fa-1d1b463c934d">

For example, it won't work if you try to load grapesjs via CDN like this `https://unpkg.com/grapesjs` (here a redirect is happening) as in this case the URL would be `https://unpkg.com/grapes.min.js.map`. It would work though if try with the full resource URL `https://unpkg.com/grapesjs@0.21.8/dist/grapes.min.js`, here the final URL would be `https://unpkg.com/grapesjs@0.21.8/dist/grapes.min.js.map` and it's correct.
