### ISSUE TITLE
BUG: The infinite canvas is increasing its height infinitely when there is an element with a min-height of 100vh

### ISSUE THREAD

**Issue by mauriciolcs** [GrapesJS/grapesjs#5674]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Arc  version 1.29.0 (46113)

### Reproducible demo link

https://grapesjs-react-custom-ui-vrkhwc.stackblitz.io

### Describe the bug

**How to reproduce the bug?**
1. Enable inifinite canvas
2. Add at least two components to the canvas
3. Set a min-height of 100vh for one of them

**What is the expected behavior?**
The height of the canvas should not increase infinitely.

**What is the current behavior?**
The canvas height is increasing infinitely.

The most straightforward method to set the min-height in this demo is using the inspector. The same error occurs when attempting to configure it through GrapesJS.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Avoid using infinite canvas as it was never documented and not even finished as a feature.
