### ISSUE TITLE
BUG: <> is introduced at the beginning editor.getHtml()

### ISSUE THREAD

**Issue by mitcht** [GrapesJS/grapesjs#5689]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Version 121.0.6167.185 (Official Build) (64-bit)

### Reproducible demo link

https://jsfiddle.net/ja50kzne/4/

### Describe the bug

**How to reproduce the bug?**
1. I had a webpage from a previous version of grapesJS that loads into grapes correctly.  You can see this in the fiddle.  The latest version of GrapesJS "created" the JSON seen in the fiddle.  I did not manipulate it.
2. Notice that grapesJS does load, no errors in the console.  
3. When performing editor.getHtml (for db storage), I see that there is an empty element `<>` being introduced
4. Note the console.log

**What is the expected behavior?**
I expect to not see `<>` at the start of the string from `editor.getHtml()`

**What is the current behavior?**
I see `<>` upon using `.editor.getHtml()`

I want to reiterate that I have not messed with the JSON.  If there is something in there, it was generated by a previous version of grapesJS.

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
See fiddle https://jsfiddle.net/ja50kzne/4/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mitcht** [comment]
I whittled the json down a quite a bit, and noticed there is some possibly invalid JSON being generated as output?

```
"components":[
                     {
                        "name":"Row",
                        "droppable":".cell",
                        "resizable":{
                           "tl":0,
                           "tc":0,
                           "tr":0,
                           "cl":0,
                           "cr":0,
                           "bl":0,
                           "br":0,
                           "minDim":1
                        },
                        "classes":[
                           "row"
                        ],
                        "attributes":{
                           "id":"ik4zj"
                        }
                     },
                     {
                        "type":"text",
                        "content":"<p style=\\""text-align":"center;\\""><em>With special appreciation for our <a href=\\""https":" target=\\""_blank\\"">Major Sponsors</a>:</em></p>\\n",
                        "attributes":{
                           "id":"in5ko"
                        }
                     }
                  ]
```

**Comment by artf** [comment]
The root component of the page should be a `wrapper`, in your case is a `textnode` (eg. this might break a lot of stuff), with an empty `tagName` (the reason behind `<>`) and for some reason `content: "undefined"`(?)
<img width="377" alt="Screenshot 2024-02-22 at 00 44 33" src="https://github.com/GrapesJS/grapesjs/assets/11614725/0e76b02e-097b-463f-a921-33250850e3f2">
I wouldn't even expect it to load but the editor is making some slight enforcements on the root component but `type` and `tagName` are extendable so can not be enforced.

Can't really help here, I can only suggest updating the JSON manually or via script. This doesn't seem to be a behavior of any previous version, so might also be related to some custom code.
