### ISSUE TITLE
BUG: Undo not working while seleting background or text color through color picker

### ISSUE THREAD

**Issue by codei20** [GrapesJS/grapesjs#5691]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Firefox 122.0.1 

### Reproducible demo link

https://grapesjs.com/demo-mjml.html

### Describe the bug

**How to reproduce the bug?**
In the official demo:  https://grapesjs.com/demo-mjml.html
1. Add a column to the canvas
2. Select the section 
3. Go to decorations and select a background color in the color picker (note: don't click on the ok button).
4. After step 3, click on the undo button without clicking anywhere else.

**What is the expected behavior?**
1. When the undo button is clicked, the background color should revert back to the previous color

**What is the current behavior?**
1. The background color stays.

Same behavior is noticed for text color as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Probably related to the mjml plugin, not the core as I can't reproduce it (I'd suggest opening an issue to the related repo).
