### ISSUE TITLE
BUG: Ability to change all margin, padding etc properties together

### ISSUE THREAD

**Issue by ravisaxena** [GrapesJS/grapesjs#5708]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome latest

### Reproducible demo link

we are running on local machine now

### Describe the bug

Hello, right now grapesjs provides built in properties like margin, padding that allow user to change each property one by one (margin-top, margin-bottom, etc).
It would be nice to have ability to change all these properties together. To have some lock button, for example, when it's enabled it will change all properties together, not one by one.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Please avoid opening BUG issues without reading the actual point of bug issues in the template.
