### ISSUE TITLE
BUG: Whitespace handling in inline elements

### ISSUE THREAD

**Issue by bernesto** [GrapesJS/grapesjs#5724]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v122

### Reproducible demo link

https://jsfiddle.net/zwo0mdqf/5/

### Describe the bug

**How to reproduce the bug?**
1. Create valid inline block elements such as span, b, i, em, etc. that use multiple space, tab(s), or line breaks as word separators.

**What is the expected behavior?**
These elements when rendered should be spaced apart by one space. HTML export whitespace should respect input whitespace.

**What is the current behavior?**
These elements are rendered in the editor as separate components, but appear as one word. Output html is stripped of input whitespace. Note: Component HTML is exported on new lines per element, so displayed output does render correctly, but getHtml() does not.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danstarns** [comment]
Closing in favor of merged commit. https://github.com/GrapesJS/grapesjs/pull/5719
