### ISSUE TITLE
BUG: The link titles are not editable

### ISSUE THREAD

**Issue by kuntal811** [GrapesJS/grapesjs#5757]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v122, Safari 17

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Add link component, try editing the link text

**What is the expected behavior?**
The link text should be editable

**What is the current behavior?**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mauzer93** [comment]
I have the same issue recently.

**Comment by artf** [comment]
Thanks for the report, will be [fixed](https://github.com/GrapesJS/grapesjs/commit/a54f213c33ee90549ef06f3b505c455f1abfc323) in the next release.
