### ISSUE TITLE
BUG: Outlines persist in preview mode

### ISSUE THREAD

**Issue by bernesto** [GrapesJS/grapesjs#5785]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v122

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

This may be by design, but it seems odd given the intent.

**How to reproduce the bug?**
1. Click preview (eye)

**What is the expected behavior?**
The page is viewable as an end user would see it. All administrative markup is removed from the page.

**What is the current behavior?**
All administrative markup 'except' the dashed outlines of components are removed. 

When in preview, `.${ppfx}dashed ` should be removed from the body, and reapplied if enabled when exiting preview. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @bernesto there is actually an update to do on the demo side. 
I prepared the change and will fix it on the next release.

**Comment by bernesto** [comment]
Awesome @artf you are a rockstar!
