### ISSUE TITLE
BUG: CSS properties default values

### ISSUE THREAD

**Issue by lexoyo** [GrapesJS/grapesjs#5788]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

N/A

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

Hi everyone !!! <3

**How to reproduce the bug?**

1. open [grapesjs official webpage demo](https://grapesjs.com/demo.html)
2. click on a container, e.g. the hero section container
3. apply a `font-weight: bold;` style to the container => all the texts inside become bold
4. select one of the texts inside, check the property `font-weight`, it is set to `normal`

**What is the expected behavior?**

`font-weight` should be on `''` empty string or `unset` so that i can select `normal` to un-apply the  `font-weight: bold;`

**What is the current behavior?**

the property `font-weight` is set to `normal` already, making it impossible for me to really apply "normal" (i need to select something else then normal again)

I work on [this issue in silex](https://github.com/silexlabs/Silex/issues/1543) (for other css properties defined in silex) with @oliviermgx, maybe we can make a PR if everyone agrees that this is a bug and the default value should be an empty string?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
> i need to select something else then normal again

Yeah in case there are no values, the default UI preselects the `default` value, but that can be easily updated
```js
editor.StyleManager.getProperty('typography', 'font-weight').set({ default: ' ' });
```

So I guess this is not a core bug but an "unexpectedly expected" behavior 🥲

**Comment by lexoyo** [comment]
Oh ok, I thought you would want the default default value to be the expected expected behaviour 😃

Thank you for the answer
