### ISSUE TITLE
BUG: Editing button text no longer works on 0.21.9

### ISSUE THREAD

**Issue by nhverstr** [GrapesJS/grapesjs#5790]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 123.0.6312.87

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Go to the demo
2. Add a new button, or scroll to the bottom (there's a submit present already)
3. Double click and try to edit the text

**What is the expected behavior?**
Text should change

**What is the current behavior?**
Text doesn't change

So, when bumping from 21.8 to 21.9 we've noticed this issue. My best guess is this was intruced in "src/trait_manager/view/TraitButtonView.ts", just based of [comparing](https://github.com/GrapesJS/grapesjs/compare/v0.21.8...v0.21.9) the commits in github. 

If I can help, I'd be happy to give it a go!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is an expected behavior of the [forms plugin](https://github.com/GrapesJS/components-forms/blob/7db2e61bceb6eda7537e293b7248b0a4b49349d3/src/components.ts#L261) (text is editable from traits)
