### ISSUE TITLE
BUG: How to add a addtional custom block manager like tab or section like block manager and style manager ,and add some blocks it to it? 

### ISSUE THREAD

**Issue by gitpugal** [GrapesJS/grapesjs#5795]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome v9

### Reproducible demo link

-

### Describe the bug

**How to reproduce the bug?**
1. ...
2. ...

**What is the expected behavior?**
...

**What is the current behavior?**
...

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
// your code here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@gitpugal please use the Discussion if you have any questions
