### ISSUE TITLE
BUG: Filtering Blocks does not work as described in Docs

### ISSUE THREAD

**Issue by rhoenerSBS** [GrapesJS/grapesjs#5803]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v123

### Reproducible demo link

https://jsfiddle.net/7xu0efLc/3/

### Describe the bug

The GrapesJs docs show that it is supposedly possible to filter the blocks and rerender the BlockManager with the filtered list of blocks. (see docs https://grapesjs.com/docs/api/block_manager.html#render) In the fiddle you can see, that it's not working. Only the Text Block should be visible.

**How to reproduce the bug?**
1. Open Fiddle or integrate filter code from linked docs in own project.

**What is the expected behavior?**
BlockManager should be able to render with filtered List of blocks.

**What is the current behavior?**
Blocks are not filtered.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
That method is only valid once the default block manager is already rendered. 
If you need to rerender at the beginning can subscribe to the event of block manager activation.
```js
editor.on('command:run:open-blocks', () => {
    const blocks = editor.BlockManager.getAll();
    const filtered = blocks.filter(block => block.getLabel() == 'Text');
    editor.BlockManager.render(filtered);
  });
```

**Comment by rhoenerSBS** [comment]
Thank you @artf
