### ISSUE TITLE
Icons and Shapes options

### ISSUE THREAD

**Issue by ajayappventure** [GrapesJS/grapesjs#5869]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

test

### Describe the bug

I don't see any way to show icons or shapes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Please use the Discussions panel if you have questions.
