### ISSUE TITLE
BUG: Unable to open component settings again, after clicking component and then clicking Blocks

### ISSUE THREAD

**Issue by gladykov** [GrapesJS/grapesjs#5905]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Opera 10.0.5130.23 | Linux

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

1. Clear canvas
2. From Blocks menu add `1 Column` component -> `Settings` tab is opened automatically :ok_hand: 
3. Click newly added component inside editor frame
4. Go to `Blocks` tab
5. Click component again

Expected:
Settings opened again

Actual:
Settings is not opened.

Note: I understand this works properly when component was not previously selected. Easy to verify this behavior by adding 2 components. But it introduces 2 different behaviors, depending on previous user action. I would expect that clicking component always opens `Settings`

Video:

https://github.com/GrapesJS/grapesjs/assets/24669884/1c652513-bc28-4226-a7c0-46fdd19d97a2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Thanks @gladykov but this is not related to the core, it's just an example behavior implemented in the demo.
