### ISSUE TITLE
BUG: SVG containing mask and image doesn't render correctly

### ISSUE THREAD

**Issue by viicslen** [GrapesJS/grapesjs#5914]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Microsoft Edge 125.0.2535.51

### Reproducible demo link

https://jsfiddle.net/szLp8h4n

### Describe the bug

**What is the expected behavior?**
Editor should render image and mask inside the SVG tag

**What is the current behavior?**
The SVG compnent has no visible content

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Please provide a valid reproducible demo
