### ISSUE TITLE
BUG: Unable to use UI controls for the video component when 

### ISSUE THREAD

**Issue by omerson-cruz** [GrapesJS/grapesjs#5922]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

v125.0.6422.113 (Official Build) (64-bit)

### Reproducible demo link

https://codesandbox.io/p/sandbox/eloquent-leaf-vd68cf?file=%2Findex.js%3A9%2C47

### Describe the bug

**How to reproduce the bug?**
1. Drag video compennt to the canvas. 
2. Select the video component and the compoennt settings/traits
3. Select "Youtube" as Provider
4. Paste the video ID of the youtube source
5. Make sure the Controls trait is enabled
6. Try to click play or adjust volume in the video component but it's not working

**What is the expected behavior?**
Expected: When VIdeo "Controls" is enabled then users will be able to use the Video UI controls like "play" , "adjust volume" etc.
...

**What is the current behavior?**
Please see the uploaded video. Thanks!
...

https://github.com/GrapesJS/grapesjs/assets/65213312/ef6a2191-d1d7-4c87-99bb-ceb4090b7018

```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You can't interact with the iframe during the editing, otherwise, it won't be possible to select it from the canvas.
You check the iframe interactions during the preview though.
