### ISSUE TITLE
BUG: GrapesJS Fails to Apply Styles to Wrapper

### ISSUE THREAD

**Issue by mcnika** [GrapesJS/grapesjs#5929]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 125.0.6422.141 

### Reproducible demo link

N/A

### Describe the bug

When setting the following configuration for the storage manager:
`storageManager: {
    autosave: false,
    autoload: false,
}`

The wrapper style is disappears ( the background color, image... ) and get only this:

`<body style="box-sizing: border-box; margin: 0;">
...`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
The reproducible demo is required for a bug report.
