### ISSUE TITLE
image send to mail  

### ISSUE THREAD

**Issue by nimisha744** [GrapesJS/grapesjs#5937]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

chrome

### Reproducible demo link

https://grapesjs.com/demo-newsletter-editor.html  https://prnt.sc/SyoEBQMUJbO8

### Describe the bug

**How to reproduce the bug?**
i am making the demo from prapes js newsletter demo and coping the html and send that into email 

 
**What is the expected behavior?**

i want to send image with that templat which i pass in email.  like this is my demo => https://prnt.sc/iTHa6Bg0IfRr
**What is the current behavior?**
now in demoview it is looking nice with images but when i send the email, image is not working there is no src passed in img tag
i am getting this in email => https://prnt.sc/HVZ7kYlHevqF
 
please help me to solve this ASAp

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
@nimisha744 issues in this repo are only for the bugs related to the core framework, demos are there only for demonstration purposes of the framework capability.

**Comment by nimisha744** [comment]
can you please help me to get this code ? https://prnt.sc/qAb-i9M5c6SF

bt this i am getting only html
let html = editor.getHtml(); also please give the options for newsletter
image and in sidebar i am getting name not icons pls share option config
setting for that
