### ISSUE TITLE
BUG:  GrapesJS CDN not working 

### ISSUE THREAD

**Issue by shahsalmanbukhari** [GrapesJS/grapesjs#5941]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 125.0.6422.113

### Reproducible demo link

<script src="https://grapesjs.com/js/toastr.min.js"></script>

### Describe the bug

**How to reproduce the bug?**
1. just click on anyone of these link, thy will show you 404 page 
```
  <script src="https://grapesjs.com/js/toastr.min.js"></script>
  <script src="https://grapesjs.com/js/grapesjs-preset-webpage.min.js"></script>
   <script src="assets/js/grapesjs-plugin-ckeditor.min.js"></script>
  <link rel="stylesheet" href="https://grapesjs.com/stylesheets/toastr.min.css">
  <link rel="stylesheet" href="https://grapesjs.com/stylesheets/grapes.min.css?v0.15.8">
  <link rel="stylesheet" href="https://grapesjs.com/stylesheets/grapesjs-preset-webpage.min.css">
  <link rel="stylesheet" href="https://grapesjs.com/stylesheets/tooltip.css">
  <link rel="stylesheet" href="https://grapesjs.com/stylesheets/demos.css">
```

**What is the expected behavior?**
It should load the files from CDN

**What is the current behavior?**
Files are not loaded from CDN

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
Np need to execute, Just click on any provided link
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Hey @shahsalmanbukhari what you're referring to is not a CDN, but simple assets on the public website. Please don't use them as there is no versioning or even guarantee they won't be moved (as it happened due to the move of the website).

Use a real CDN as https://unpkg.com/grapesjs

**Comment by shahsalmanbukhari** [comment]
> Hey @shahsalmanbukhari what you're referring to is not a CDN, but simple assets on the public website. Please don't use them as there is no versioning or even guarantee they won't be moved (as it happened due to the move of the website).
> 
> Use a real CDN as https://unpkg.com/grapesjs

Hi @artf 
Thanks a lot, let me try your suggested solution
