### ISSUE TITLE
BUG: Component styles such as md:flex-row(tailwind) are removed

### ISSUE THREAD

**Issue by ihatov08** [GrapesJS/grapesjs#5982]
### GrapesJS version

- [x] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 126.0.6478.127

### Reproducible demo link

https://jsfiddle.net/6m53pwy7/4/

### Describe the bug

**How to reproduce the bug?**
I'm looking to use [Tailwind](https://tailwindcss.com/) with GrapesJS, but this framework uses Utility-First CSS Classes to build quick layouts. The problem is that it also uses ['special' classes](https://tailwindcss.com/docs/state-variants/#app) to define style variants, eg: hover:bg-blue or md:w-full etc.
Styles that include colons such as md:flex-row hover:bg-black in the component style will be deleted.
You can check by looking at "view code"

**What is the expected behavior?**

```js
domc.addType('hero-section-1', {
  model: {
    defaults: {
      attributes: { class: 'hero-section-1' },
      components: `
  <div class="md:p-18">
  </div>
      `,
      styles: `
  @media (min-width: 768px) {
    .md\:p-18 { padding: 4rem; }
  }
      `
    },
  },
})
```

view code 👇

```html
<body id="icsl">
  <div class="hero-section-1">
    <div class="md:p-18">
    </div>
  </div>
</body>
```

```css
  @media (min-width: 768px) {
    .md\:p-18 { padding: 4rem; }
  }
```

**What is the current behavior?**

```js
domc.addType('hero-section-1', {
  model: {
    defaults: {
      attributes: { class: 'hero-section-1' },
      components: `
  <div class="md:p-18">
  </div>
      `,
      styles: `
  @media (min-width: 768px) {
    .md\:p-18 { padding: 4rem; }
  }
      `
    },
  },
})
```

![image](https://github.com/GrapesJS/grapesjs/assets/14024165/33c9660a-84d0-437d-9833-6a49905d7301)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
You need to escape properly the CSS
```js
.md\\:p-18 { padding: 4rem; }
```
