### ISSUE TITLE
Categorize Traits similar to Blocks

### ISSUE THREAD

**Issue by z1lk** [GrapesJS/grapesjs#679]
I'm building the Bootstrap plugin and have a growing list of utility settings for basically every component. Add component-specific and ARIA settings on top of that, and the Settings panel becomes pretty cramped. Can we have the ability to categorize settings into "collapses" like with Blocks?

I'd be willing to contribute a PR if we can do this by simply copying the Blocks categories code.

**Comment by artf** [comment]
Thanks @z1lk for the suggestion, it definitely makes sense but I'm not sure about copying stuff, I'd like to avoid repeating code, probably it would make sense create an abstract view which does the same thing and which we can use in other points

**Comment by artf** [comment]
Closing this in favor of https://github.com/GrapesJS/grapesjs/issues/1806
